<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_IoHiQJF1EeqYh62qYTdhOg" name="ST-Diagrama de Solucion Tecnica" version="2.0.0" author="Mireya" bonitaVersion="7.10.1" bonitaModelVersion="7.10.0-001" configId="ACED0005740010372E31302E302D303031372E31302E31">
    <elements xmi:type="process:Pool" xmi:id="_IoHiQZF1EeqYh62qYTdhOg" name="Proceso de Solucion Tecnica" version="2.0.0">
      <elements xmi:type="process:Lane" xmi:id="_IoHiQpF1EeqYh62qYTdhOg" name="Preventa" actor="_IoIKJJF1EeqYh62qYTdhOg">
        <elements xmi:type="process:StartEvent" xmi:id="_IoHiQ5F1EeqYh62qYTdhOg" name="Inicio" outgoing="_IoIJx5F1EeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoHiRJF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoHiRZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoHiRpF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_IoHiR5F1EeqYh62qYTdhOg" name="¿Existen lideres asignados?" outgoing="_IoIJypF1EeqYh62qYTdhOg _IoIJzZF1EeqYh62qYTdhOg" incoming="_IoIJx5F1EeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoHiSJF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoHiSZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoHiSpF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_IoHiS5F1EeqYh62qYTdhOg" name="Asignar Gerencia Operativa" outgoing="_IoIJ05F1EeqYh62qYTdhOg" incoming="_IoIKHpF1EeqYh62qYTdhOg" type="PARALLEL">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoHiTJF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoHiTZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoHiTpF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IoHiT5F1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IoHiUJF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IoHiUZF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IoHiUpF1EeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IoHiU5F1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_IoHiVJF1EeqYh62qYTdhOg" name="Proceso de Asignacion de Gerencia Operativa" content="Proceso de Asignacion de Gerencia Operativa" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_IoHiVZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_IoHiVpF1EeqYh62qYTdhOg" name="Obtener lista de Arquitectos" outgoing="_IoIJ0JF1EeqYh62qYTdhOg" incoming="_IoIJzZF1EeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoHiV5F1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoHiWJF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoHiWZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IoHiWpF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IoHiW5F1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IoHiXJF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IoHiXZF1EeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IoHiXpF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_IoHiX5F1EeqYh62qYTdhOg" name="Compuerta1" outgoing="_IoIJ1pF1EeqYh62qYTdhOg" incoming="_IoIJ0JF1EeqYh62qYTdhOg _IoIJ05F1EeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoHiYJF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoHiYZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoHiYpF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_IoHikpF1EeqYh62qYTdhOg" name="Obtener Lista de Preventa" outgoing="_IoIKHpF1EeqYh62qYTdhOg" incoming="_IoIJypF1EeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoHik5F1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoHilJF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoHilZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IoHilpF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IoHil5F1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IoHimJF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IoHimZF1EeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IoHimpF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_5jD1AJOgEeqcrv5mpi41Dg" name="Notificación Reunión de Kick Off" outgoing="_PRbzsJOmEeqcrv5mpi41Dg" incoming="_IoIJ1pF1EeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1wN1gZOgEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1wN1gJOgEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1wN1gpOgEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_c_x8wJPXEeqcrv5mpi41Dg" name="Notificación de Tarea" definitionId="email" event="ON_FINISH" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_c_x8wZPXEeqcrv5mpi41Dg" definitionId="email" version="1.1.0" modelVersion="7.10.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x8wpPXEeqcrv5mpi41Dg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_c_x8w5PXEeqcrv5mpi41Dg" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x8xJPXEeqcrv5mpi41Dg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_c_x8xZPXEeqcrv5mpi41Dg" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x8xpPXEeqcrv5mpi41Dg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_c_x8x5PXEeqcrv5mpi41Dg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x8yJPXEeqcrv5mpi41Dg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_c_x8yZPXEeqcrv5mpi41Dg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x8ypPXEeqcrv5mpi41Dg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_c_x8y5PXEeqcrv5mpi41Dg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x8zJPXEeqcrv5mpi41Dg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_c_x8zZPXEeqcrv5mpi41Dg" name="$$Dhst_23" content="$$Dhst_23" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x8zpPXEeqcrv5mpi41Dg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_c_x8z5PXEeqcrv5mpi41Dg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x80JPXEeqcrv5mpi41Dg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_c_x80ZPXEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x80pPXEeqcrv5mpi41Dg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_c_x805PXEeqcrv5mpi41Dg" name="opacheco@hightech-corp.com" content="opacheco@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x81JPXEeqcrv5mpi41Dg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_c_x81ZPXEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x81pPXEeqcrv5mpi41Dg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_c_x815PXEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x82JPXEeqcrv5mpi41Dg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_c_x82ZPXEeqcrv5mpi41Dg" name="Notificación de tarea" content="Notificación de tarea" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x82pPXEeqcrv5mpi41Dg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_c_x825PXEeqcrv5mpi41Dg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x83JPXEeqcrv5mpi41Dg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_c_x83ZPXEeqcrv5mpi41Dg" name="&lt;pattern-expression>" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x83pPXEeqcrv5mpi41Dg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_c_x835PXEeqcrv5mpi41Dg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x84JPXEeqcrv5mpi41Dg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_c_x84ZPXEeqcrv5mpi41Dg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x84pPXEeqcrv5mpi41Dg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_c_x845PXEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c_x85JPXEeqcrv5mpi41Dg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_c_x85ZPXEeqcrv5mpi41Dg"/>
              </parameters>
            </configuration>
          </connectors>
          <operations xmi:type="expression:Operation" xmi:id="_tJe-QJlIEeqapZnVVpuk4A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_tJe-QZlIEeqapZnVVpuk4A" name="docsObj" content="docsObj" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:JavaObjectData" xmi:id="_ttcm8JlIEeqapZnVVpuk4A" name="docsObj" dataType="_IoIKO5F1EeqYh62qYTdhOg" className="java.util.List"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_tJe-QplIEeqapZnVVpuk4A" name="documentsSolucionTecnica" content="documentsSolucionTecnica" type="TYPE_DOCUMENT" returnType="java.util.List">
              <referencedElements xmi:type="process:Document" xmi:id="_uE6rwJlIEeqapZnVVpuk4A" name="documentsSolucionTecnica" multiple="true"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_tJe-Q5lIEeqapZnVVpuk4A" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_1wN1g5OgEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_1wN1hJOgEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_1wN1hZOgEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_1wN1h5OgEeqcrv5mpi41Dg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_1wN1hpOgEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_IoHim5F1EeqYh62qYTdhOg" name="Arquitecto">
        <elements xmi:type="process:Task" xmi:id="_IoHinJF1EeqYh62qYTdhOg" name="Revisar Proyecto Asignado " outgoing="_IoIJ3JF1EeqYh62qYTdhOg" incoming="_IoIKA5F1EeqYh62qYTdhOg" type="PARALLEL" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoHinZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoHinpF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoHin5F1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IoHioJF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IoHioZF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IoHiopF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IoHio5F1EeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IoHipJF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_IoHipZF1EeqYh62qYTdhOg">
            <targetForm xmi:type="expression:Expression" xmi:id="_IoHippF1EeqYh62qYTdhOg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_IoHip5F1EeqYh62qYTdhOg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_IoHiqJF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_IoHiqZF1EeqYh62qYTdhOg" name="Solicitar reunión con el cliente" outgoing="_IoIJ2ZF1EeqYh62qYTdhOg" incoming="_IoIJ3JF1EeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoHiqpF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoHiq5F1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoHirJF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_IoHirZF1EeqYh62qYTdhOg" name="Notificación de Tarea" definitionId="email" event="ON_FINISH" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_IoHirpF1EeqYh62qYTdhOg" definitionId="email" version="1.1.0" modelVersion="7.10.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHir5F1EeqYh62qYTdhOg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_IoHisJF1EeqYh62qYTdhOg" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHisZF1EeqYh62qYTdhOg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_IoHispF1EeqYh62qYTdhOg" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHis5F1EeqYh62qYTdhOg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_IoHitJF1EeqYh62qYTdhOg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHitZF1EeqYh62qYTdhOg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_IoHitpF1EeqYh62qYTdhOg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHit5F1EeqYh62qYTdhOg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_IoHiuJF1EeqYh62qYTdhOg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHiuZF1EeqYh62qYTdhOg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_IoHiupF1EeqYh62qYTdhOg" name="$$Dhst_23" content="$$Dhst_23" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHiu5F1EeqYh62qYTdhOg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_IoHivJF1EeqYh62qYTdhOg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHivZF1EeqYh62qYTdhOg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_IoHivpF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHiv5F1EeqYh62qYTdhOg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_IoHiwJF1EeqYh62qYTdhOg" name="opacheco@hightech-corp.com" content="opacheco@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHiwZF1EeqYh62qYTdhOg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_IoHiwpF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHiw5F1EeqYh62qYTdhOg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_IoHixJF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHixZF1EeqYh62qYTdhOg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_IoHixpF1EeqYh62qYTdhOg" name="Notificación de Tarea" content="Notificación de Tarea" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHix5F1EeqYh62qYTdhOg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_IoHiyJF1EeqYh62qYTdhOg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHiyZF1EeqYh62qYTdhOg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_IoHiypF1EeqYh62qYTdhOg" name="&lt;pattern-expression>" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHiy5F1EeqYh62qYTdhOg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_IoHizJF1EeqYh62qYTdhOg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHizZF1EeqYh62qYTdhOg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_IoHizpF1EeqYh62qYTdhOg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHiz5F1EeqYh62qYTdhOg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_IoHi0JF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHi0ZF1EeqYh62qYTdhOg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_IoHi0pF1EeqYh62qYTdhOg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IoHi05F1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IoHi1JF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IoHi1ZF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IoHi1pF1EeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IoHi15F1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_IoHi2JF1EeqYh62qYTdhOg" name="Elaboración  SDD" outgoing="_IoIJ35F1EeqYh62qYTdhOg" incoming="_f7awAJF9EeqYh62qYTdhOg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoHi2ZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoHi2pF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoHi25F1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IoHi3JF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IoHi3ZF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IoHi3pF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IoHi35F1EeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IoHi4JF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_IoHi4ZF1EeqYh62qYTdhOg">
            <targetForm xmi:type="expression:Expression" xmi:id="_IoHi4pF1EeqYh62qYTdhOg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_IoHi45F1EeqYh62qYTdhOg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_IoHi5JF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_IoHi5ZF1EeqYh62qYTdhOg" name="Notificación Conformación de Comité" outgoing="_IoIJ4pF1EeqYh62qYTdhOg" incoming="_XKf1IJYsEeq2K99SrQ8DiQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoHi5pF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoHi55F1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoHi6JF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_IoHi6ZF1EeqYh62qYTdhOg" name="Notificación de Tarea" definitionId="email" event="ON_FINISH" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_IoHi6pF1EeqYh62qYTdhOg" definitionId="email" version="1.1.0" modelVersion="7.10.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHi65F1EeqYh62qYTdhOg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_IoHi7JF1EeqYh62qYTdhOg" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHi7ZF1EeqYh62qYTdhOg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_IoHi7pF1EeqYh62qYTdhOg" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHi75F1EeqYh62qYTdhOg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_IoHi8JF1EeqYh62qYTdhOg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHi8ZF1EeqYh62qYTdhOg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_IoHi8pF1EeqYh62qYTdhOg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHi85F1EeqYh62qYTdhOg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_IoHi9JF1EeqYh62qYTdhOg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHi9ZF1EeqYh62qYTdhOg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_IoHi9pF1EeqYh62qYTdhOg" name="$$Dhst_23" content="$$Dhst_23" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHi95F1EeqYh62qYTdhOg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_IoHi-JF1EeqYh62qYTdhOg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHi-ZF1EeqYh62qYTdhOg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_IoHi-pF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHi-5F1EeqYh62qYTdhOg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_IoHi_JF1EeqYh62qYTdhOg" name="opacheco@hightech-corp.com" content="opacheco@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHi_ZF1EeqYh62qYTdhOg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_IoHi_pF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHi_5F1EeqYh62qYTdhOg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_IoHjAJF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHjAZF1EeqYh62qYTdhOg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_IoHjApF1EeqYh62qYTdhOg" name="Notificación de Tarea" content="Notificación de Tarea" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHjA5F1EeqYh62qYTdhOg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_IoHjBJF1EeqYh62qYTdhOg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHjBZF1EeqYh62qYTdhOg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_IoHjBpF1EeqYh62qYTdhOg" name="&lt;pattern-expression>" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHjB5F1EeqYh62qYTdhOg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_IoHjCJF1EeqYh62qYTdhOg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHjCZF1EeqYh62qYTdhOg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_IoHjCpF1EeqYh62qYTdhOg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHjC5F1EeqYh62qYTdhOg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_IoHjDJF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHjDZF1EeqYh62qYTdhOg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_IoHjDpF1EeqYh62qYTdhOg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IoHjD5F1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IoHjEJF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IoHjEZF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IoHjEpF1EeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IoHjE5F1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_IoHjFJF1EeqYh62qYTdhOg" name="Modificación SDD" outgoing="_5QR5kJYqEeq2K99SrQ8DiQ" incoming="_IoIKG5F1EeqYh62qYTdhOg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoHjFZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoHjFpF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoHjF5F1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IoHjGJF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IoHjGZF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IoHjGpF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IoHjG5F1EeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IoHjHJF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_IoHjHZF1EeqYh62qYTdhOg">
            <targetForm xmi:type="expression:Expression" xmi:id="_IoHjHpF1EeqYh62qYTdhOg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_IoHjH5F1EeqYh62qYTdhOg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_IoHjIJF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_IoHjIZF1EeqYh62qYTdhOg" name="¿Esta Aprobado por el Cliente?" outgoing="_IoIJ7pF1EeqYh62qYTdhOg _IoIKGJF1EeqYh62qYTdhOg" incoming="_IoIKFZF1EeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoHjIpF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoHjI5F1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoHjJJF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_IoHjJZF1EeqYh62qYTdhOg" name="Entregar versión preliminar SDD" outgoing="_IbLZcJYKEeq2K99SrQ8DiQ" incoming="_IoIJ7pF1EeqYh62qYTdhOg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoHjJpF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoHjJ5F1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoHjKJF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IoHjKZF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IoHjKpF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IoHjK5F1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IoHjLJF1EeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IoHjLZF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_IoHjLpF1EeqYh62qYTdhOg">
            <targetForm xmi:type="expression:Expression" xmi:id="_IoHjL5F1EeqYh62qYTdhOg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_IoHjMJF1EeqYh62qYTdhOg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_IoHjMZF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_IoIJapF1EeqYh62qYTdhOg" name="¿Existe SDD?" outgoing="_IoIKFZF1EeqYh62qYTdhOg _BjfZAJPSEeqcrv5mpi41Dg" incoming="_IoIKBpF1EeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoIJa5F1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoIJbJF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoIJbZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_IoIJbpF1EeqYh62qYTdhOg" name="Compuerta5" outgoing="_IoIKG5F1EeqYh62qYTdhOg" incoming="_IoIJ6JF1EeqYh62qYTdhOg _IoIKGJF1EeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoIJb5F1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoIJcJF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoIJcZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_HO9sEJF3EeqYh62qYTdhOg" name="¿Requiere Apoyo de Cómite de Arquitectura?" outgoing="_HQpHEJF3EeqYh62qYTdhOg _QRA7YJF3EeqYh62qYTdhOg" incoming="_IoIJ35F1EeqYh62qYTdhOg _5QR5kJYqEeq2K99SrQ8DiQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HPKgYZF3EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HPKgYJF3EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HPKgYpF3EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_JMm9IJF6EeqYh62qYTdhOg" name="Asignar Comité Arquitectura" outgoing="_dzrIkJYsEeq2K99SrQ8DiQ" incoming="_IoIJ4pF1EeqYh62qYTdhOg" type="PARALLEL">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EwA2AZF6EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EwA2AJF6EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EwA2ApF6EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_EwA2A5F6EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_EwA2BJF6EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EwA2BZF6EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_EwA2B5F6EeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_EwA2BpF6EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_JMnkM5F6EeqYh62qYTdhOg" name="ST-Proceso de de Asignacion de Comite de Arquitectura" content="ST-Proceso de de Asignacion de Comite de Arquitectura" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_JMnkNJF6EeqYh62qYTdhOg" name="1.0.0" content="1.0.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ABYcUJF9EeqYh62qYTdhOg" name="¿Existe comité?" outgoing="_OWoDkJF9EeqYh62qYTdhOg _XKf1IJYsEeq2K99SrQ8DiQ" incoming="_HQpHEJF3EeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ABZDYZF9EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ABZDYJF9EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ABZDYpF9EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_f7TbQJF9EeqYh62qYTdhOg" name="Colaborar en Elaboración SDD" outgoing="_f7awAJF9EeqYh62qYTdhOg" incoming="_nGWwgJOdEeqcrv5mpi41Dg" type="PARALLEL">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_f7UpYJF9EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_f7UCUJF9EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_f7UpYZF9EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_f7UpYpF9EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_f7UpY5F9EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_f7UpZJF9EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_f7UpZpF9EeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_f7UpZZF9EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ISG4MJGEEeqYh62qYTdhOg" name="Compuerta7" outgoing="_ISLwsJGEEeqYh62qYTdhOg" incoming="_OWoDkJF9EeqYh62qYTdhOg _dzrIkJYsEeq2K99SrQ8DiQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ISHfQZGEEeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ISHfQJGEEeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ISHfQpGEEeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_ZjGTUJGOEeqYh62qYTdhOg" name="Notificación de Revisión" outgoing="_ZjLy4JGOEeqYh62qYTdhOg" incoming="_ISLwsJGEEeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZjGTUpGOEeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZjGTUZGOEeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZjGTU5GOEeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_men_UJPjEeqcrv5mpi41Dg" name="Notificación de tarea" definitionId="email" event="ON_FINISH" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_men_UZPjEeqcrv5mpi41Dg" definitionId="email" version="1.1.0" modelVersion="7.10.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_men_UpPjEeqcrv5mpi41Dg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_men_U5PjEeqcrv5mpi41Dg" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_men_VJPjEeqcrv5mpi41Dg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_men_VZPjEeqcrv5mpi41Dg" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_men_VpPjEeqcrv5mpi41Dg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_men_V5PjEeqcrv5mpi41Dg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_men_WJPjEeqcrv5mpi41Dg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_men_WZPjEeqcrv5mpi41Dg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_men_WpPjEeqcrv5mpi41Dg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_men_W5PjEeqcrv5mpi41Dg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_men_XJPjEeqcrv5mpi41Dg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_men_XZPjEeqcrv5mpi41Dg" name="$$Dhst_23" content="$$Dhst_23" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_men_XpPjEeqcrv5mpi41Dg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_men_X5PjEeqcrv5mpi41Dg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_men_YJPjEeqcrv5mpi41Dg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_men_YZPjEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_men_YpPjEeqcrv5mpi41Dg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_men_Y5PjEeqcrv5mpi41Dg" name="opacheco@hightech-corp.com" content="opacheco@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_men_ZJPjEeqcrv5mpi41Dg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_men_ZZPjEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_men_ZpPjEeqcrv5mpi41Dg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_men_Z5PjEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_men_aJPjEeqcrv5mpi41Dg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_men_aZPjEeqcrv5mpi41Dg" name="Notificación de Tarea" content="Notificación de Tarea" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_men_apPjEeqcrv5mpi41Dg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_men_a5PjEeqcrv5mpi41Dg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_men_bJPjEeqcrv5mpi41Dg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_men_bZPjEeqcrv5mpi41Dg" name="&lt;pattern-expression>" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_men_bpPjEeqcrv5mpi41Dg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_men_b5PjEeqcrv5mpi41Dg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_meomYJPjEeqcrv5mpi41Dg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_meomYZPjEeqcrv5mpi41Dg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_meomYpPjEeqcrv5mpi41Dg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_meomY5PjEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_meomZJPjEeqcrv5mpi41Dg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_meomZZPjEeqcrv5mpi41Dg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ZjGTVJGOEeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ZjG6YJGOEeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ZjG6YZGOEeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ZjG6Y5GOEeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ZjG6YpGOEeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_nGONoJOdEeqcrv5mpi41Dg" name="Notificación de Colaborar en SDD" outgoing="_nGWwgJOdEeqcrv5mpi41Dg" incoming="_BjfZAJPSEeqcrv5mpi41Dg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nGO0sZOdEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nGO0sJOdEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nGO0spOdEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_N3MWkJPjEeqcrv5mpi41Dg" name="Notificación de Tarea" definitionId="email" event="ON_FINISH" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_N3MWkZPjEeqcrv5mpi41Dg" definitionId="email" version="1.1.0" modelVersion="7.10.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWkpPjEeqcrv5mpi41Dg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_N3MWk5PjEeqcrv5mpi41Dg" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWlJPjEeqcrv5mpi41Dg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_N3MWlZPjEeqcrv5mpi41Dg" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWlpPjEeqcrv5mpi41Dg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_N3MWl5PjEeqcrv5mpi41Dg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWmJPjEeqcrv5mpi41Dg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_N3MWmZPjEeqcrv5mpi41Dg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWmpPjEeqcrv5mpi41Dg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_N3MWm5PjEeqcrv5mpi41Dg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWnJPjEeqcrv5mpi41Dg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_N3MWnZPjEeqcrv5mpi41Dg" name="$$Dhst_23" content="$$Dhst_23" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWnpPjEeqcrv5mpi41Dg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_N3MWn5PjEeqcrv5mpi41Dg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWoJPjEeqcrv5mpi41Dg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_N3MWoZPjEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWopPjEeqcrv5mpi41Dg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_N3MWo5PjEeqcrv5mpi41Dg" name="opacheco@hightech-corp.com" content="opacheco@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWpJPjEeqcrv5mpi41Dg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_N3MWpZPjEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWppPjEeqcrv5mpi41Dg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_N3MWp5PjEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWqJPjEeqcrv5mpi41Dg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_N3MWqZPjEeqcrv5mpi41Dg" name="Notificación de Tarea" content="Notificación de Tarea" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWqpPjEeqcrv5mpi41Dg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_N3MWq5PjEeqcrv5mpi41Dg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWrJPjEeqcrv5mpi41Dg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_N3MWrZPjEeqcrv5mpi41Dg" name="&lt;pattern-expression>" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWrpPjEeqcrv5mpi41Dg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_N3MWr5PjEeqcrv5mpi41Dg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWsJPjEeqcrv5mpi41Dg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_N3MWsZPjEeqcrv5mpi41Dg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWspPjEeqcrv5mpi41Dg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_N3MWs5PjEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N3MWtJPjEeqcrv5mpi41Dg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_N3MWtZPjEeqcrv5mpi41Dg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_nGO0s5OdEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_nGO0tJOdEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_nGO0tZOdEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_nGO0t5OdEeqcrv5mpi41Dg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_nGO0tpOdEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_IoHiY5F1EeqYh62qYTdhOg" name="Notificación Revisión de proyecto" outgoing="_IoIKA5F1EeqYh62qYTdhOg" incoming="_qHhZoJPYEeqcrv5mpi41Dg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoHiZJF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoHiZZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoHiZpF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_IoHiZ5F1EeqYh62qYTdhOg" name="Notificación de tarea" definitionId="email" event="ON_FINISH" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_IoHiaJF1EeqYh62qYTdhOg" definitionId="email" version="1.1.0" modelVersion="7.10.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHiaZF1EeqYh62qYTdhOg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_IoHiapF1EeqYh62qYTdhOg" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHia5F1EeqYh62qYTdhOg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_IoHibJF1EeqYh62qYTdhOg" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHibZF1EeqYh62qYTdhOg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_IoHibpF1EeqYh62qYTdhOg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHib5F1EeqYh62qYTdhOg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_IoHicJF1EeqYh62qYTdhOg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHicZF1EeqYh62qYTdhOg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_IoHicpF1EeqYh62qYTdhOg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHic5F1EeqYh62qYTdhOg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_IoHidJF1EeqYh62qYTdhOg" name="$$Dhst_23" content="$$Dhst_23" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHidZF1EeqYh62qYTdhOg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_IoHidpF1EeqYh62qYTdhOg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHid5F1EeqYh62qYTdhOg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_IoHieJF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHieZF1EeqYh62qYTdhOg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_IoHiepF1EeqYh62qYTdhOg" name="opacheco@hightech-corp.com" content="opacheco@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHie5F1EeqYh62qYTdhOg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_IoHifJF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHifZF1EeqYh62qYTdhOg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_IoHifpF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHif5F1EeqYh62qYTdhOg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_IoHigJF1EeqYh62qYTdhOg" name="Notificacion" content="Notificacion" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHigZF1EeqYh62qYTdhOg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_IoHigpF1EeqYh62qYTdhOg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHig5F1EeqYh62qYTdhOg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_IoHihJF1EeqYh62qYTdhOg" name="&lt;pattern-expression>" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHihZF1EeqYh62qYTdhOg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_IoHihpF1EeqYh62qYTdhOg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHih5F1EeqYh62qYTdhOg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_IoHiiJF1EeqYh62qYTdhOg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHiiZF1EeqYh62qYTdhOg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_IoHiipF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoHii5F1EeqYh62qYTdhOg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_IoHijJF1EeqYh62qYTdhOg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IoHijZF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IoHijpF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IoHij5F1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IoHikJF1EeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IoHikZF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_IoIJhJF1EeqYh62qYTdhOg" name="Notificación de Solicitud de Reunión" outgoing="_IoIKDJF1EeqYh62qYTdhOg" incoming="_aKkZcJGCEeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoIJhZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoIJhpF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoIJh5F1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_IoIJiJF1EeqYh62qYTdhOg" name="Notificación de Tarea" definitionId="email" event="ON_FINISH" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_IoIJiZF1EeqYh62qYTdhOg" definitionId="email" version="1.1.0" modelVersion="7.10.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJipF1EeqYh62qYTdhOg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_IoIJi5F1EeqYh62qYTdhOg" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJjJF1EeqYh62qYTdhOg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_IoIJjZF1EeqYh62qYTdhOg" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJjpF1EeqYh62qYTdhOg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_IoIJj5F1EeqYh62qYTdhOg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJkJF1EeqYh62qYTdhOg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_IoIJkZF1EeqYh62qYTdhOg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJkpF1EeqYh62qYTdhOg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_IoIJk5F1EeqYh62qYTdhOg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJlJF1EeqYh62qYTdhOg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_IoIJlZF1EeqYh62qYTdhOg" name="$$Dhst_23" content="$$Dhst_23" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJlpF1EeqYh62qYTdhOg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_IoIJl5F1EeqYh62qYTdhOg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJmJF1EeqYh62qYTdhOg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_IoIJmZF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJmpF1EeqYh62qYTdhOg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_IoIJm5F1EeqYh62qYTdhOg" name="opacheco@hightech-corp.com" content="opacheco@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJnJF1EeqYh62qYTdhOg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_IoIJnZF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJnpF1EeqYh62qYTdhOg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_IoIJn5F1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJoJF1EeqYh62qYTdhOg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_IoIJoZF1EeqYh62qYTdhOg" name="Notificación de Tarea" content="Notificación de Tarea" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJopF1EeqYh62qYTdhOg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_IoIJo5F1EeqYh62qYTdhOg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJpJF1EeqYh62qYTdhOg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_IoIJpZF1EeqYh62qYTdhOg" name="&lt;pattern-expression>" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJppF1EeqYh62qYTdhOg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_IoIJp5F1EeqYh62qYTdhOg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJqJF1EeqYh62qYTdhOg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_IoIJqZF1EeqYh62qYTdhOg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJqpF1EeqYh62qYTdhOg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_IoIJq5F1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IoIJrJF1EeqYh62qYTdhOg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_IoIJrZF1EeqYh62qYTdhOg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IoIJrpF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IoIJr5F1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IoIJsJF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IoIJsZF1EeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IoIJspF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_IoIJs5F1EeqYh62qYTdhOg" name="Compuerta4" outgoing="_IoIKD5F1EeqYh62qYTdhOg" incoming="_IoIJ2ZF1EeqYh62qYTdhOg _IoIKDJF1EeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoIJtJF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoIJtZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoIJtpF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_aKdrwJGCEeqYh62qYTdhOg" name="Compuerta6" outgoing="_aKkZcJGCEeqYh62qYTdhOg" incoming="_QRA7YJF3EeqYh62qYTdhOg _IoIKCZF1EeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_aKdrwpGCEeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_aKdrwZGCEeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_aKdrw5GCEeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_IoIJcpF1EeqYh62qYTdhOg" name="Comité Arquitectura">
        <elements xmi:type="process:Task" xmi:id="_IoIJc5F1EeqYh62qYTdhOg" name="Revisión SDD" outgoing="_IoIJ5ZF1EeqYh62qYTdhOg" incoming="_2opkoJF3EeqYh62qYTdhOg _ZjLy4JGOEeqYh62qYTdhOg" type="PARALLEL" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoIJdJF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoIJdZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoIJdpF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IoIJd5F1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IoIJeJF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IoIJeZF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IoIJepF1EeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IoIJe5F1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_IoIJfJF1EeqYh62qYTdhOg">
            <targetForm xmi:type="expression:Expression" xmi:id="_IoIJfZF1EeqYh62qYTdhOg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_IoIJfpF1EeqYh62qYTdhOg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_IoIJf5F1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_IoIJgJF1EeqYh62qYTdhOg" name="¿Comité Presenta Observaciones?" outgoing="_IoIJ6JF1EeqYh62qYTdhOg _IoIKCZF1EeqYh62qYTdhOg" incoming="_IoIJ5ZF1EeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoIJgZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoIJgpF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoIJg5F1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_IoIJt5F1EeqYh62qYTdhOg" name="PMO">
        <elements xmi:type="process:CallActivity" xmi:id="_IoIJuJF1EeqYh62qYTdhOg" name="Gestionar reunión con  cliente " outgoing="_IoIKBpF1EeqYh62qYTdhOg" incoming="_IoIKD5F1EeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoIJuZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoIJupF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoIJu5F1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IoIJvJF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IoIJvZF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IoIJvpF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IoIJv5F1EeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IoIJwJF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_IoIJwZF1EeqYh62qYTdhOg" name="ST-Proceso de Gestion de Reunion Cliente" content="ST-Proceso de Gestion de Reunion Cliente" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_IoIJwpF1EeqYh62qYTdhOg" name="1.0.0" content="1.0.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="__TnsIJOlEeqcrv5mpi41Dg" name="Asignar Arquitecto Lider" outgoing="_u5NSsJOmEeqcrv5mpi41Dg" incoming="_XAb0AJPYEeqcrv5mpi41Dg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-vK7QZOlEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-vK7QJOlEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-vK7QpOlEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-vK7Q5OlEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-vK7RJOlEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_-vK7RZOlEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_-vLiUJOlEeqcrv5mpi41Dg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_-vK7RpOlEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="__ToTMJOlEeqcrv5mpi41Dg">
            <targetForm xmi:type="expression:Expression" xmi:id="__ToTMZOlEeqcrv5mpi41Dg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="__TnsKZOlEeqcrv5mpi41Dg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__ToTMpOlEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_en870JPUEeqcrv5mpi41Dg" name="Gestionar fecha reunión Kick Off" outgoing="_eoKXMJPUEeqcrv5mpi41Dg" incoming="_PRbzsJOmEeqcrv5mpi41Dg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_en-J8ZPUEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_en-J8JPUEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_en-J8pPUEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_wWd3oJlIEeqapZnVVpuk4A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wWd3oZlIEeqapZnVVpuk4A" name="objSolicitudPrev" content="objSolicitudPrev" type="TYPE_VARIABLE" returnType="com.htc.model.SolicitudProy">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wWd3oplIEeqapZnVVpuk4A" name="objSolicitudPrev" dataType="_IoIKPZF1EeqYh62qYTdhOg" className="com.htc.model.SolicitudProy"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wWd3o5lIEeqapZnVVpuk4A" name="objSolicitudPrevInput.fechaIngreso" content="objSolicitudPrevInput?.fechaIngreso" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wWd3pJlIEeqapZnVVpuk4A" name="objSolicitudPrevInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wWd3pZlIEeqapZnVVpuk4A" type="JAVA_METHOD" expression="setFechaIngreso">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_en-J85PUEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_en-J9JPUEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_en-J9ZPUEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_en-J95PUEeqcrv5mpi41Dg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_en-J9pPUEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_en-J-ZPUEeqcrv5mpi41Dg">
            <targetForm xmi:type="expression:Expression" xmi:id="_x9BlwJlIEeqapZnVVpuk4A" name="kikoForm" content="ef4796bf-9412-46c2-ab78-2be0bb0fd760" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_en-J-JPUEeqcrv5mpi41Dg">
            <inputs xmi:type="process:ContractInput" xmi:id="_wWdQkJlIEeqapZnVVpuk4A" name="objSolicitudPrevInput" type="COMPLEX" dataReference="objSolicitudPrev" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_wWdQkZlIEeqapZnVVpuk4A" name="fechaIngreso" type="LOCALDATE" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_en-J-5PUEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_lzOPsJPUEeqcrv5mpi41Dg" name="Notificación  fecha Reunión kick Off" outgoing="_lzWLgJPUEeqcrv5mpi41Dg" incoming="_eoKXMJPUEeqcrv5mpi41Dg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lzO2wZPUEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lzO2wJPUEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lzO2wpPUEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_ynlysJPXEeqcrv5mpi41Dg" name="Notificación de Tarea" definitionId="email" event="ON_FINISH" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_ynlysZPXEeqcrv5mpi41Dg" definitionId="email" version="1.1.0" modelVersion="7.10.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynlyspPXEeqcrv5mpi41Dg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_ynlys5PXEeqcrv5mpi41Dg" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynlytJPXEeqcrv5mpi41Dg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_ynlytZPXEeqcrv5mpi41Dg" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynlytpPXEeqcrv5mpi41Dg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_ynlyt5PXEeqcrv5mpi41Dg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynlyuJPXEeqcrv5mpi41Dg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_ynlyuZPXEeqcrv5mpi41Dg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynlyupPXEeqcrv5mpi41Dg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_ynlyu5PXEeqcrv5mpi41Dg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynlyvJPXEeqcrv5mpi41Dg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_ynlyvZPXEeqcrv5mpi41Dg" name="$$Dhst_23" content="$$Dhst_23" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynlyvpPXEeqcrv5mpi41Dg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_ynlyv5PXEeqcrv5mpi41Dg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynlywJPXEeqcrv5mpi41Dg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_ynlywZPXEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynlywpPXEeqcrv5mpi41Dg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_ynlyw5PXEeqcrv5mpi41Dg" name="opacheco@hightech-corp.com" content="opacheco@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynlyxJPXEeqcrv5mpi41Dg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_ynlyxZPXEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynlyxpPXEeqcrv5mpi41Dg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_ynlyx5PXEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynlyyJPXEeqcrv5mpi41Dg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_ynlyyZPXEeqcrv5mpi41Dg" name="Notificación de Tarea" content="Notificación de Tarea" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynlyypPXEeqcrv5mpi41Dg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_ynlyy5PXEeqcrv5mpi41Dg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynlyzJPXEeqcrv5mpi41Dg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_ynlyzZPXEeqcrv5mpi41Dg" name="&lt;pattern-expression>" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynlyzpPXEeqcrv5mpi41Dg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_ynlyz5PXEeqcrv5mpi41Dg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynly0JPXEeqcrv5mpi41Dg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_ynly0ZPXEeqcrv5mpi41Dg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynly0pPXEeqcrv5mpi41Dg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_ynly05PXEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ynly1JPXEeqcrv5mpi41Dg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_ynly1ZPXEeqcrv5mpi41Dg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_lzO2w5PUEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_lzO2xJPUEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_lzO2xZPUEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_lzO2x5PUEeqcrv5mpi41Dg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_lzO2xpPUEeqcrv5mpi41Dg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_XAVGUJPYEeqcrv5mpi41Dg" name="¿Existe más de un Arquitecto?" outgoing="_XAb0AJPYEeqcrv5mpi41Dg _201ZwJPYEeqcrv5mpi41Dg" incoming="_lzWLgJPUEeqcrv5mpi41Dg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XAVtYZPYEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XAVtYJPYEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XAVtYpPYEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_qHchIJPYEeqcrv5mpi41Dg" name="Compuerta9" outgoing="_qHhZoJPYEeqcrv5mpi41Dg" incoming="_u5NSsJOmEeqcrv5mpi41Dg _nw8RsJYmEeq2K99SrQ8DiQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qHdIMZPYEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qHdIMJPYEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qHdIMpPYEeqcrv5mpi41Dg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_IoHjMpF1EeqYh62qYTdhOg" name="Notificación entrega SDD- versión preliminar" outgoing="_IoIJ95F1EeqYh62qYTdhOg" incoming="_IbLZcJYKEeq2K99SrQ8DiQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoHjM5F1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoHjNJF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoHjNZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="__BZ8IJPkEeqcrv5mpi41Dg" name="Notificación de Tarea " definitionId="email" event="ON_FINISH" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="__BZ8IZPkEeqcrv5mpi41Dg" definitionId="email" version="1.1.0" modelVersion="7.10.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8IpPkEeqcrv5mpi41Dg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="__BZ8I5PkEeqcrv5mpi41Dg" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8JJPkEeqcrv5mpi41Dg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="__BZ8JZPkEeqcrv5mpi41Dg" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8JpPkEeqcrv5mpi41Dg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="__BZ8J5PkEeqcrv5mpi41Dg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8KJPkEeqcrv5mpi41Dg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="__BZ8KZPkEeqcrv5mpi41Dg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8KpPkEeqcrv5mpi41Dg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="__BZ8K5PkEeqcrv5mpi41Dg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8LJPkEeqcrv5mpi41Dg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="__BZ8LZPkEeqcrv5mpi41Dg" name="$$Dhst_23" content="$$Dhst_23" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8LpPkEeqcrv5mpi41Dg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="__BZ8L5PkEeqcrv5mpi41Dg" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8MJPkEeqcrv5mpi41Dg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="__BZ8MZPkEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8MpPkEeqcrv5mpi41Dg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="__BZ8M5PkEeqcrv5mpi41Dg" name="opacheco@hightech-corp.com" content="opacheco@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8NJPkEeqcrv5mpi41Dg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="__BZ8NZPkEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8NpPkEeqcrv5mpi41Dg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="__BZ8N5PkEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8OJPkEeqcrv5mpi41Dg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="__BZ8OZPkEeqcrv5mpi41Dg" name="Notificación de Tarea" content="Notificación de Tarea" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8OpPkEeqcrv5mpi41Dg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="__BZ8O5PkEeqcrv5mpi41Dg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8PJPkEeqcrv5mpi41Dg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="__BZ8PZPkEeqcrv5mpi41Dg" name="&lt;pattern-expression>" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8PpPkEeqcrv5mpi41Dg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="__BZ8P5PkEeqcrv5mpi41Dg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8QJPkEeqcrv5mpi41Dg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="__BZ8QZPkEeqcrv5mpi41Dg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8QpPkEeqcrv5mpi41Dg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="__BZ8Q5PkEeqcrv5mpi41Dg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__BZ8RJPkEeqcrv5mpi41Dg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="__BZ8RZPkEeqcrv5mpi41Dg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IoHjNpF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IoHjN5F1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IoHjOJF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IoHjOZF1EeqYh62qYTdhOg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IoHjOpF1EeqYh62qYTdhOg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_IoIJZpF1EeqYh62qYTdhOg" name="Fin del Proceso" incoming="_IoIJ95F1EeqYh62qYTdhOg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IoIJZ5F1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IoIJaJF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IoIJaZF1EeqYh62qYTdhOg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_nwmTcJYmEeq2K99SrQ8DiQ" name="Asignar Automáticamente Arquitecto Lider" outgoing="_nw8RsJYmEeq2K99SrQ8DiQ" incoming="_201ZwJPYEeqcrv5mpi41Dg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nwzu0ZYmEeq2K99SrQ8DiQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nwzu0JYmEeq2K99SrQ8DiQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nwzu0pYmEeq2K99SrQ8DiQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_nwzu05YmEeq2K99SrQ8DiQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_nwzu1JYmEeq2K99SrQ8DiQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_nwzu1ZYmEeq2K99SrQ8DiQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_nw0V4JYmEeq2K99SrQ8DiQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_nwzu1pYmEeq2K99SrQ8DiQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_C-3yoJlIEeqRvP2LHW5_IA" name="solicitudProy" dataType="_IoIKPZF1EeqYh62qYTdhOg" className="com.htc.model.SolicitudProy">
        <defaultValue xmi:type="expression:Expression" xmi:id="_RhcrQJlIEeqRvP2LHW5_IA" name="initSolicitudProy()" content="def solicitudProyVar = new com.htc.model.SolicitudProy()&#xD;&#xA;solicitudProyVar.nombreProyecto = solicitudProyInput?.nombreProyecto&#xD;&#xA;solicitudProyVar.fechaPresentacion = solicitudProyInput?.fechaPresentacion&#xD;&#xA;solicitudProyVar.salesCloudId = solicitudProyInput?.salesCloudId&#xD;&#xA;solicitudProyVar.salesCloudDate = solicitudProyInput?.salesCloudDate&#xD;&#xA;solicitudProyVar.pipeline = solicitudProyInput?.pipeline&#xD;&#xA;solicitudProyVar.alcance = solicitudProyInput?.alcance&#xD;&#xA;solicitudProyVar.consideracion = solicitudProyInput?.consideracion&#xD;&#xA;return solicitudProyVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.htc.model.SolicitudProy">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_RhcrQZlIEeqRvP2LHW5_IA" name="solicitudProyInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_IoIJw5F1EeqYh62qYTdhOg">
        <targetForm xmi:type="expression:Expression" xmi:id="_IoIJxJF1EeqYh62qYTdhOg" name="newForm" content="4a937e24-f430-406c-aaf6-fb71b6eef3f8" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_IoIJxZF1EeqYh62qYTdhOg">
        <targetForm xmi:type="expression:Expression" xmi:id="_IoIJxpF1EeqYh62qYTdhOg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIJx5F1EeqYh62qYTdhOg" target="_IoHiR5F1EeqYh62qYTdhOg" source="_IoHiQ5F1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIJyJF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIJyZF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIJypF1EeqYh62qYTdhOg" name="No" target="_IoHikpF1EeqYh62qYTdhOg" source="_IoHiR5F1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIJy5F1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIJzJF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIJzZF1EeqYh62qYTdhOg" name="Si" target="_IoHiVpF1EeqYh62qYTdhOg" source="_IoHiR5F1EeqYh62qYTdhOg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIJzpF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIJz5F1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIJ0JF1EeqYh62qYTdhOg" target="_IoHiX5F1EeqYh62qYTdhOg" source="_IoHiVpF1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIJ0ZF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIJ0pF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIJ05F1EeqYh62qYTdhOg" target="_IoHiX5F1EeqYh62qYTdhOg" source="_IoHiS5F1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIJ1JF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIJ1ZF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIJ1pF1EeqYh62qYTdhOg" target="_5jD1AJOgEeqcrv5mpi41Dg" source="_IoHiX5F1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIJ15F1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIJ2JF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIJ2ZF1EeqYh62qYTdhOg" target="_IoIJs5F1EeqYh62qYTdhOg" source="_IoHiqZF1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIJ2pF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIJ25F1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIJ3JF1EeqYh62qYTdhOg" target="_IoHiqZF1EeqYh62qYTdhOg" source="_IoHinJF1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIJ3ZF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIJ3pF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIJ35F1EeqYh62qYTdhOg" target="_HO9sEJF3EeqYh62qYTdhOg" source="_IoHi2JF1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIJ4JF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIJ4ZF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIJ4pF1EeqYh62qYTdhOg" target="_JMm9IJF6EeqYh62qYTdhOg" source="_IoHi5ZF1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIJ45F1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIJ5JF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIJ5ZF1EeqYh62qYTdhOg" target="_IoIJgJF1EeqYh62qYTdhOg" source="_IoIJc5F1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIJ5pF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIJ55F1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIJ6JF1EeqYh62qYTdhOg" name="Si" target="_IoIJbpF1EeqYh62qYTdhOg" source="_IoIJgJF1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIJ6ZF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIJ6pF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIJ7pF1EeqYh62qYTdhOg" name="Si" target="_IoHjJZF1EeqYh62qYTdhOg" source="_IoHjIZF1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIJ75F1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIJ8JF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIJ95F1EeqYh62qYTdhOg" target="_IoIJZpF1EeqYh62qYTdhOg" source="_IoHjMpF1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIJ-JF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIJ-ZF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIKA5F1EeqYh62qYTdhOg" target="_IoHinJF1EeqYh62qYTdhOg" source="_IoHiY5F1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIKBJF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIKBZF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIKBpF1EeqYh62qYTdhOg" target="_IoIJapF1EeqYh62qYTdhOg" source="_IoIJuJF1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIKB5F1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIKCJF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIKCZF1EeqYh62qYTdhOg" name="No" target="_aKdrwJGCEeqYh62qYTdhOg" source="_IoIJgJF1EeqYh62qYTdhOg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIKCpF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIKC5F1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIKDJF1EeqYh62qYTdhOg" target="_IoIJs5F1EeqYh62qYTdhOg" source="_IoIJhJF1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIKDZF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIKDpF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIKD5F1EeqYh62qYTdhOg" target="_IoIJuJF1EeqYh62qYTdhOg" source="_IoIJs5F1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIKEJF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIKEZF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIKFZF1EeqYh62qYTdhOg" name="Si" target="_IoHjIZF1EeqYh62qYTdhOg" source="_IoIJapF1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIKFpF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIKF5F1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIKGJF1EeqYh62qYTdhOg" name="No" target="_IoIJbpF1EeqYh62qYTdhOg" source="_IoHjIZF1EeqYh62qYTdhOg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIKGZF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIKGpF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIKG5F1EeqYh62qYTdhOg" target="_IoHjFJF1EeqYh62qYTdhOg" source="_IoIJbpF1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIKHJF1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIKHZF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IoIKHpF1EeqYh62qYTdhOg" target="_IoHiS5F1EeqYh62qYTdhOg" source="_IoHikpF1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IoIKH5F1EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IoIKIJF1EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HQpHEJF3EeqYh62qYTdhOg" name="Si" target="_ABYcUJF9EeqYh62qYTdhOg" source="_HO9sEJF3EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HQpuIJF3EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_HQqVMJF3EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QRA7YJF3EeqYh62qYTdhOg" name="No" target="_aKdrwJGCEeqYh62qYTdhOg" source="_HO9sEJF3EeqYh62qYTdhOg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QRA7YZF3EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_QRA7YpF3EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2opkoJF3EeqYh62qYTdhOg" target="_IoIJc5F1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2opkoZF3EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_2oqLsJF3EeqYh62qYTdhOg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OWoDkJF9EeqYh62qYTdhOg" name="Si" target="_ISG4MJGEEeqYh62qYTdhOg" source="_ABYcUJF9EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OWoDkZF9EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_OWoDkpF9EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_f7awAJF9EeqYh62qYTdhOg" target="_IoHi2JF1EeqYh62qYTdhOg" source="_f7TbQJF9EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_f7awAZF9EeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_f7awApF9EeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aKkZcJGCEeqYh62qYTdhOg" target="_IoIJhJF1EeqYh62qYTdhOg" source="_aKdrwJGCEeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aKkZcZGCEeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_aKkZcpGCEeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ISLwsJGEEeqYh62qYTdhOg" target="_ZjGTUJGOEeqYh62qYTdhOg" source="_ISG4MJGEEeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ISLwsZGEEeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_ISLwspGEEeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZjLy4JGOEeqYh62qYTdhOg" target="_IoIJc5F1EeqYh62qYTdhOg" source="_ZjGTUJGOEeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZjLy4ZGOEeqYh62qYTdhOg"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZjLy4pGOEeqYh62qYTdhOg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nGWwgJOdEeqcrv5mpi41Dg" target="_f7TbQJF9EeqYh62qYTdhOg" source="_nGONoJOdEeqcrv5mpi41Dg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nGXXkJOdEeqcrv5mpi41Dg"/>
        <condition xmi:type="expression:Expression" xmi:id="_nGXXkZOdEeqcrv5mpi41Dg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PRbzsJOmEeqcrv5mpi41Dg" target="_en870JPUEeqcrv5mpi41Dg" source="_5jD1AJOgEeqcrv5mpi41Dg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PRcawJOmEeqcrv5mpi41Dg"/>
        <condition xmi:type="expression:Expression" xmi:id="_PRcawZOmEeqcrv5mpi41Dg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_u5NSsJOmEeqcrv5mpi41Dg" target="_qHchIJPYEeqcrv5mpi41Dg" source="__TnsIJOlEeqcrv5mpi41Dg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_u5NSsZOmEeqcrv5mpi41Dg"/>
        <condition xmi:type="expression:Expression" xmi:id="_u5NSspOmEeqcrv5mpi41Dg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BjfZAJPSEeqcrv5mpi41Dg" name="No" target="_nGONoJOdEeqcrv5mpi41Dg" source="_IoIJapF1EeqYh62qYTdhOg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BjgnIJPSEeqcrv5mpi41Dg"/>
        <condition xmi:type="expression:Expression" xmi:id="_BjgnIZPSEeqcrv5mpi41Dg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_eoKXMJPUEeqcrv5mpi41Dg" target="_lzOPsJPUEeqcrv5mpi41Dg" source="_en870JPUEeqcrv5mpi41Dg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_eoKXMZPUEeqcrv5mpi41Dg"/>
        <condition xmi:type="expression:Expression" xmi:id="_eoKXMpPUEeqcrv5mpi41Dg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lzWLgJPUEeqcrv5mpi41Dg" target="_XAVGUJPYEeqcrv5mpi41Dg" source="_lzOPsJPUEeqcrv5mpi41Dg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lzWLgZPUEeqcrv5mpi41Dg"/>
        <condition xmi:type="expression:Expression" xmi:id="_lzWLgpPUEeqcrv5mpi41Dg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XAb0AJPYEeqcrv5mpi41Dg" name="Si" target="__TnsIJOlEeqcrv5mpi41Dg" source="_XAVGUJPYEeqcrv5mpi41Dg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XAb0AZPYEeqcrv5mpi41Dg"/>
        <condition xmi:type="expression:Expression" xmi:id="_XAb0ApPYEeqcrv5mpi41Dg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qHhZoJPYEeqcrv5mpi41Dg" target="_IoHiY5F1EeqYh62qYTdhOg" source="_qHchIJPYEeqcrv5mpi41Dg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qHhZoZPYEeqcrv5mpi41Dg"/>
        <condition xmi:type="expression:Expression" xmi:id="_qHhZopPYEeqcrv5mpi41Dg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_201ZwJPYEeqcrv5mpi41Dg" name="No" target="_nwmTcJYmEeq2K99SrQ8DiQ" source="_XAVGUJPYEeqcrv5mpi41Dg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_202A0JPYEeqcrv5mpi41Dg"/>
        <condition xmi:type="expression:Expression" xmi:id="_202A0ZPYEeqcrv5mpi41Dg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IbLZcJYKEeq2K99SrQ8DiQ" target="_IoHjMpF1EeqYh62qYTdhOg" source="_IoHjJZF1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IbydcJYKEeq2K99SrQ8DiQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_IbzEgJYKEeq2K99SrQ8DiQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nw8RsJYmEeq2K99SrQ8DiQ" target="_qHchIJPYEeqcrv5mpi41Dg" source="_nwmTcJYmEeq2K99SrQ8DiQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nw8RsZYmEeq2K99SrQ8DiQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_nw8RspYmEeq2K99SrQ8DiQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5QR5kJYqEeq2K99SrQ8DiQ" target="_HO9sEJF3EeqYh62qYTdhOg" source="_IoHjFJF1EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5QR5kZYqEeq2K99SrQ8DiQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_5QR5kpYqEeq2K99SrQ8DiQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XKf1IJYsEeq2K99SrQ8DiQ" name="No" target="_IoHi5ZF1EeqYh62qYTdhOg" source="_ABYcUJF9EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XKgcMJYsEeq2K99SrQ8DiQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_XKgcMZYsEeq2K99SrQ8DiQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dzrIkJYsEeq2K99SrQ8DiQ" target="_ISG4MJGEEeqYh62qYTdhOg" source="_JMm9IJF6EeqYh62qYTdhOg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dzrIkZYsEeq2K99SrQ8DiQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_dzrIkpYsEeq2K99SrQ8DiQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_IoIKJJF1EeqYh62qYTdhOg" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_IoIKJZF1EeqYh62qYTdhOg">
        <inputs xmi:type="process:ContractInput" xmi:id="_RhbdIJlIEeqRvP2LHW5_IA" name="solicitudProyInput" type="COMPLEX" dataReference="solicitudProy">
          <inputs xmi:type="process:ContractInput" xmi:id="_RhcEMJlIEeqRvP2LHW5_IA" name="nombreProyecto"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_RhcEMZlIEeqRvP2LHW5_IA" name="fechaPresentacion" type="LOCALDATE"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_RhcEMplIEeqRvP2LHW5_IA" name="salesCloudId"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_RhcEM5lIEeqRvP2LHW5_IA" name="salesCloudDate" type="LOCALDATE"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_RhcENJlIEeqRvP2LHW5_IA" name="pipeline" type="DECIMAL"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_RhcENZlIEeqRvP2LHW5_IA" name="alcance"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_RhcENplIEeqRvP2LHW5_IA" name="consideracion"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_IoIKJpF1EeqYh62qYTdhOg">
        <name xmi:type="expression:Expression" xmi:id="_IoIKJ5F1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_IoIKKJF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_IoIKKZF1EeqYh62qYTdhOg">
        <name xmi:type="expression:Expression" xmi:id="_IoIKKpF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_IoIKK5F1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_IoIKLJF1EeqYh62qYTdhOg">
        <name xmi:type="expression:Expression" xmi:id="_IoIKLZF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_IoIKLpF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_IoIKL5F1EeqYh62qYTdhOg">
        <name xmi:type="expression:Expression" xmi:id="_IoIKMJF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_IoIKMZF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_IoIKMpF1EeqYh62qYTdhOg">
        <name xmi:type="expression:Expression" xmi:id="_IoIKM5F1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_IoIKNJF1EeqYh62qYTdhOg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_IoIKNZF1EeqYh62qYTdhOg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_IoIKNpF1EeqYh62qYTdhOg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_IoIKN5F1EeqYh62qYTdhOg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_IoIKOJF1EeqYh62qYTdhOg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_IoIKOZF1EeqYh62qYTdhOg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_IoIKOpF1EeqYh62qYTdhOg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_IoIKO5F1EeqYh62qYTdhOg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_IoIKPJF1EeqYh62qYTdhOg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_IoIKPZF1EeqYh62qYTdhOg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_IoIKPpF1EeqYh62qYTdhOg" type="Process" element="_IoHiQJF1EeqYh62qYTdhOg" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_IoIKP5F1EeqYh62qYTdhOg" type="2007" element="_IoHiQZF1EeqYh62qYTdhOg">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIKQJF1EeqYh62qYTdhOg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIKQZF1EeqYh62qYTdhOg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_IoIKQpF1EeqYh62qYTdhOg" type="3007" element="_IoHiQpF1EeqYh62qYTdhOg">
          <children xmi:type="notation:DecorationNode" xmi:id="_IoIKQ5F1EeqYh62qYTdhOg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_IoIKRJF1EeqYh62qYTdhOg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_IoIKRZF1EeqYh62qYTdhOg" type="3002" element="_IoHiQ5F1EeqYh62qYTdhOg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKRpF1EeqYh62qYTdhOg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIKR5F1EeqYh62qYTdhOg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKSJF1EeqYh62qYTdhOg" x="86" y="105"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKSZF1EeqYh62qYTdhOg" type="3008" element="_IoHiR5F1EeqYh62qYTdhOg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKSpF1EeqYh62qYTdhOg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIKS5F1EeqYh62qYTdhOg" x="11" y="-69"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKTJF1EeqYh62qYTdhOg" x="223" y="98" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKTZF1EeqYh62qYTdhOg" type="3063" element="_IoHiS5F1EeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKTpF1EeqYh62qYTdhOg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKT5F1EeqYh62qYTdhOg" x="326" y="234" width="140" height="71"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKUJF1EeqYh62qYTdhOg" type="3027" element="_IoHiVpF1EeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKUZF1EeqYh62qYTdhOg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKUpF1EeqYh62qYTdhOg" x="476" y="90" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKU5F1EeqYh62qYTdhOg" type="3008" element="_IoHiX5F1EeqYh62qYTdhOg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKVJF1EeqYh62qYTdhOg" visible="false" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIKVZF1EeqYh62qYTdhOg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKVpF1EeqYh62qYTdhOg" x="525" y="248"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKWpF1EeqYh62qYTdhOg" type="3027" element="_IoHikpF1EeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKW5F1EeqYh62qYTdhOg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKXJF1EeqYh62qYTdhOg" x="185" y="177" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5jFDIJOgEeqcrv5mpi41Dg" type="3027" element="_5jD1AJOgEeqcrv5mpi41Dg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5jFDIpOgEeqcrv5mpi41Dg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5jFDIZOgEeqcrv5mpi41Dg" x="80" y="331" width="121" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_IoIKXZF1EeqYh62qYTdhOg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_IoIKXpF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_IoIKX5F1EeqYh62qYTdhOg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_IoIKYJF1EeqYh62qYTdhOg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKYZF1EeqYh62qYTdhOg" x="48" y="10" width="1955" height="451"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_IoIKYpF1EeqYh62qYTdhOg" type="3007" element="_IoHim5F1EeqYh62qYTdhOg">
          <children xmi:type="notation:DecorationNode" xmi:id="_IoIKY5F1EeqYh62qYTdhOg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_IoIKZJF1EeqYh62qYTdhOg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_IoIKZZF1EeqYh62qYTdhOg" type="3005" element="_IoHinJF1EeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKZpF1EeqYh62qYTdhOg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKZ5F1EeqYh62qYTdhOg" x="213" y="32" width="133" height="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKaJF1EeqYh62qYTdhOg" type="3027" element="_IoHiqZF1EeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKaZF1EeqYh62qYTdhOg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKapF1EeqYh62qYTdhOg" x="371" y="342" width="127" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKa5F1EeqYh62qYTdhOg" type="3005" element="_IoHi2JF1EeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKbJF1EeqYh62qYTdhOg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKbZF1EeqYh62qYTdhOg" x="550" y="160" width="132" height="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKbpF1EeqYh62qYTdhOg" type="3027" element="_IoHi5ZF1EeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKb5F1EeqYh62qYTdhOg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKcJF1EeqYh62qYTdhOg" x="1118" y="70" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKcZF1EeqYh62qYTdhOg" type="3005" element="_IoHjFJF1EeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKcpF1EeqYh62qYTdhOg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKc5F1EeqYh62qYTdhOg" x="1296" y="13" width="116" height="58"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKdJF1EeqYh62qYTdhOg" type="3008" element="_IoHjIZF1EeqYh62qYTdhOg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKdZF1EeqYh62qYTdhOg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIKdpF1EeqYh62qYTdhOg" x="21" y="6"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKd5F1EeqYh62qYTdhOg" x="1144" y="484" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKeJF1EeqYh62qYTdhOg" type="3005" element="_IoHjJZF1EeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKeZF1EeqYh62qYTdhOg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKepF1EeqYh62qYTdhOg" x="1089" y="602" width="146" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKkZF1EeqYh62qYTdhOg" type="3008" element="_IoIJapF1EeqYh62qYTdhOg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKkpF1EeqYh62qYTdhOg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIKk5F1EeqYh62qYTdhOg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKlJF1EeqYh62qYTdhOg" x="594" y="488"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKlZF1EeqYh62qYTdhOg" type="3008" element="_IoIJbpF1EeqYh62qYTdhOg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKlpF1EeqYh62qYTdhOg" visible="false" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIKl5F1EeqYh62qYTdhOg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKmJF1EeqYh62qYTdhOg" x="1332" y="484"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HPhFsJF3EeqYh62qYTdhOg" type="3008" element="_HO9sEJF3EeqYh62qYTdhOg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_HPi64JF3EeqYh62qYTdhOg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_HPi64ZF3EeqYh62qYTdhOg" x="-11" y="13"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HPhFsZF3EeqYh62qYTdhOg" x="817" y="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_JMoLQJF6EeqYh62qYTdhOg" type="3063" element="_JMm9IJF6EeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_JMoLQpF6EeqYh62qYTdhOg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JMoLQZF6EeqYh62qYTdhOg" x="1117" y="163" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ABZqcJF9EeqYh62qYTdhOg" type="3008" element="_ABYcUJF9EeqYh62qYTdhOg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ABZqcpF9EeqYh62qYTdhOg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ABZqc5F9EeqYh62qYTdhOg" y="-59"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ABZqcZF9EeqYh62qYTdhOg" x="973" y="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_f7VQcJF9EeqYh62qYTdhOg" type="3006" element="_f7TbQJF9EeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_f7VQcpF9EeqYh62qYTdhOg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f7VQcZF9EeqYh62qYTdhOg" x="545" y="260" width="132" height="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ISHfQ5GEEeqYh62qYTdhOg" type="3008" element="_ISG4MJGEEeqYh62qYTdhOg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ISIGUJGEEeqYh62qYTdhOg" visible="false" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ISIGUZGEEeqYh62qYTdhOg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ISHfRJGEEeqYh62qYTdhOg" x="973" y="171"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZjHhcJGOEeqYh62qYTdhOg" type="3027" element="_ZjGTUJGOEeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZjHhcpGOEeqYh62qYTdhOg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZjHhcZGOEeqYh62qYTdhOg" x="935" y="260" width="133" height="65"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_nGPbwJOdEeqcrv5mpi41Dg" type="3027" element="_nGONoJOdEeqcrv5mpi41Dg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_nGQC0JOdEeqcrv5mpi41Dg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nGPbwZOdEeqcrv5mpi41Dg" x="550" y="374" width="131" height="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKV5F1EeqYh62qYTdhOg" type="3027" element="_IoHiY5F1EeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKWJF1EeqYh62qYTdhOg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKWZF1EeqYh62qYTdhOg" x="213" y="344" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKqJF1EeqYh62qYTdhOg" type="3027" element="_IoIJhJF1EeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKqZF1EeqYh62qYTdhOg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKqpF1EeqYh62qYTdhOg" x="650" y="602" width="138" height="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKq5F1EeqYh62qYTdhOg" type="3008" element="_IoIJs5F1EeqYh62qYTdhOg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKrJF1EeqYh62qYTdhOg" visible="false" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIKrZF1EeqYh62qYTdhOg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKrpF1EeqYh62qYTdhOg" x="413" y="617"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_aKe54JGCEeqYh62qYTdhOg" type="3008" element="_aKdrwJGCEeqYh62qYTdhOg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_aKe54pGCEeqYh62qYTdhOg" visible="false" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_aKe545GCEeqYh62qYTdhOg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_aKe54ZGCEeqYh62qYTdhOg" x="817" y="617"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_IoIKmZF1EeqYh62qYTdhOg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_IoIKmpF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_IoIKm5F1EeqYh62qYTdhOg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_IoIKnJF1EeqYh62qYTdhOg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKnZF1EeqYh62qYTdhOg" x="48" y="430" width="1955" height="718"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_IoIKnpF1EeqYh62qYTdhOg" type="3007" element="_IoIJcpF1EeqYh62qYTdhOg">
          <children xmi:type="notation:DecorationNode" xmi:id="_IoIKn5F1EeqYh62qYTdhOg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_IoIKoJF1EeqYh62qYTdhOg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_IoIKoZF1EeqYh62qYTdhOg" type="3005" element="_IoIJc5F1EeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKopF1EeqYh62qYTdhOg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKo5F1EeqYh62qYTdhOg" x="948" y="30" width="132" height="65"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKpJF1EeqYh62qYTdhOg" type="3008" element="_IoIJgJF1EeqYh62qYTdhOg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKpZF1EeqYh62qYTdhOg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIKppF1EeqYh62qYTdhOg" x="1" y="6"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKp5F1EeqYh62qYTdhOg" x="992" y="125" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_IoIKr5F1EeqYh62qYTdhOg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_IoIKsJF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_IoIKsZF1EeqYh62qYTdhOg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_IoIKspF1EeqYh62qYTdhOg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKs5F1EeqYh62qYTdhOg" x="48" y="978" width="1955" height="233"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_IoIKtJF1EeqYh62qYTdhOg" type="3007" element="_IoIJt5F1EeqYh62qYTdhOg">
          <children xmi:type="notation:DecorationNode" xmi:id="_IoIKtZF1EeqYh62qYTdhOg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_IoIKtpF1EeqYh62qYTdhOg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_IoIKt5F1EeqYh62qYTdhOg" type="3063" element="_IoIJuJF1EeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKuJF1EeqYh62qYTdhOg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKuZF1EeqYh62qYTdhOg" x="546" y="32" width="149" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__ToTM5OlEeqcrv5mpi41Dg" type="3005" element="__TnsIJOlEeqcrv5mpi41Dg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__ToTNZOlEeqcrv5mpi41Dg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__ToTNJOlEeqcrv5mpi41Dg" x="430" y="354" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_en_YEJPUEeqcrv5mpi41Dg" type="3005" element="_en870JPUEeqcrv5mpi41Dg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_en__IJPUEeqcrv5mpi41Dg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_en_YEZPUEeqcrv5mpi41Dg" x="68" y="37" width="133" height="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_lzPd0JPUEeqcrv5mpi41Dg" type="3027" element="_lzOPsJPUEeqcrv5mpi41Dg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_lzQE4JPUEeqcrv5mpi41Dg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lzPd0ZPUEeqcrv5mpi41Dg" x="78" y="143" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XAWUcJPYEeqcrv5mpi41Dg" type="3008" element="_XAVGUJPYEeqcrv5mpi41Dg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_XAW7gJPYEeqcrv5mpi41Dg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_XAW7gZPYEeqcrv5mpi41Dg" x="12" y="6"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XAWUcZPYEeqcrv5mpi41Dg" x="113" y="256"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qHdvQJPYEeqcrv5mpi41Dg" type="3008" element="_qHchIJPYEeqcrv5mpi41Dg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_qHdvQpPYEeqcrv5mpi41Dg" visible="false" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_qHdvQ5PYEeqcrv5mpi41Dg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qHdvQZPYEeqcrv5mpi41Dg" x="254" y="127"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKe5F1EeqYh62qYTdhOg" type="3027" element="_IoHjMpF1EeqYh62qYTdhOg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKfJF1EeqYh62qYTdhOg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKfZF1EeqYh62qYTdhOg" x="1092" y="45" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IoIKjZF1EeqYh62qYTdhOg" type="3062" element="_IoIJZpF1EeqYh62qYTdhOg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_IoIKjpF1EeqYh62qYTdhOg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIKj5F1EeqYh62qYTdhOg" y="24"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKkJF1EeqYh62qYTdhOg" x="1429" y="55"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_nw1kAJYmEeq2K99SrQ8DiQ" type="3027" element="_nwmTcJYmEeq2K99SrQ8DiQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_nw2LEJYmEeq2K99SrQ8DiQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nw1kAZYmEeq2K99SrQ8DiQ" x="213" y="241" width="148" height="73"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_IoIKupF1EeqYh62qYTdhOg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_IoIKu5F1EeqYh62qYTdhOg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_IoIKvJF1EeqYh62qYTdhOg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_IoIKvZF1EeqYh62qYTdhOg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKvpF1EeqYh62qYTdhOg" x="48" y="1402" width="1955" height="496"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_IoIKv5F1EeqYh62qYTdhOg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIKwJF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_IoIKwZF1EeqYh62qYTdhOg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_IoIKwpF1EeqYh62qYTdhOg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIKw5F1EeqYh62qYTdhOg" width="1700" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_IoIKxJF1EeqYh62qYTdhOg"/>
    <edges xmi:type="notation:Connector" xmi:id="_IoIKxZF1EeqYh62qYTdhOg" type="4001" element="_IoIJx5F1EeqYh62qYTdhOg" source="_IoIKRZF1EeqYh62qYTdhOg" target="_IoIKSZF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIKxpF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIKx5F1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIKyJF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIKyZF1EeqYh62qYTdhOg" points="[14, -1, -129, 0]$[122, -1, -21, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIKypF1EeqYh62qYTdhOg" type="4001" element="_IoIJypF1EeqYh62qYTdhOg" source="_IoIKSZF1EeqYh62qYTdhOg" target="_IoIKWpF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIKy5F1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIKzJF1EeqYh62qYTdhOg" x="-6" y="-9"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIKzZF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIKzpF1EeqYh62qYTdhOg" points="[0, 22, -1, -50]$[0, 44, -1, -28]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIKz5F1EeqYh62qYTdhOg" type="4001" element="_IoIJzZF1EeqYh62qYTdhOg" source="_IoIKSZF1EeqYh62qYTdhOg" target="_IoIKUJF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIK0JF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIK0ZF1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIK0pF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIK05F1EeqYh62qYTdhOg" points="[22, 0, -286, -1]$[248, 0, -60, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIK1JF1EeqYh62qYTdhOg" type="4001" element="_IoIJ0JF1EeqYh62qYTdhOg" source="_IoIKUJF1EeqYh62qYTdhOg" target="_IoIKU5F1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIK1ZF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIK1pF1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIK15F1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIwYJF1EeqYh62qYTdhOg" points="[-50, 33, -14, -127]$[-50, 139, -14, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIwYZF1EeqYh62qYTdhOg" id="(1.0,0.45)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIwYpF1EeqYh62qYTdhOg" id="(0.813953488372093,0.4883720930232558)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIwY5F1EeqYh62qYTdhOg" type="4001" element="_IoIJ05F1EeqYh62qYTdhOg" source="_IoIKTZF1EeqYh62qYTdhOg" target="_IoIKU5F1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIwZJF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIwZZF1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIwZpF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIwZ5F1EeqYh62qYTdhOg" points="[0, 11, -59, 12]$[50, 11, -9, 12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIwaJF1EeqYh62qYTdhOg" id="(1.0,0.35064935064935066)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIwaZF1EeqYh62qYTdhOg" id="(0.20930232558139536,0.20930232558139536)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIwapF1EeqYh62qYTdhOg" type="4001" element="_IoIJ1pF1EeqYh62qYTdhOg" source="_IoIKU5F1EeqYh62qYTdhOg" target="_5jFDIJOgEeqcrv5mpi41Dg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIwa5F1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIwbJF1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIwbZF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIwbpF1EeqYh62qYTdhOg" points="[-22, 11, 406, -70]$[-22, 75, 406, -6]$[-367, 75, 61, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIwb5F1EeqYh62qYTdhOg" id="(1.0,0.7441860465116279)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIwcJF1EeqYh62qYTdhOg" type="4001" element="_IoIJ2ZF1EeqYh62qYTdhOg" source="_IoIKaJF1EeqYh62qYTdhOg" target="_IoIKq5F1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIwcZF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIwcpF1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIwc5F1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIwdJF1EeqYh62qYTdhOg" points="[-64, 31, 2, -186]$[-64, 208, 2, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIwdZF1EeqYh62qYTdhOg" id="(1.0,0.5079365079365079)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIwdpF1EeqYh62qYTdhOg" id="(0.4418604651162791,0.20930232558139536)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIwd5F1EeqYh62qYTdhOg" type="4001" element="_IoIJ3JF1EeqYh62qYTdhOg" source="_IoIKZZF1EeqYh62qYTdhOg" target="_IoIKaJF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIweJF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIweZF1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIwepF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIwe5F1EeqYh62qYTdhOg" points="[0, 0, -95, -316]$[95, 0, 0, -316]$[95, 285, 0, -31]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIwfJF1EeqYh62qYTdhOg" id="(1.0,0.3787878787878788)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIwfZF1EeqYh62qYTdhOg" type="4001" element="_IoIJ35F1EeqYh62qYTdhOg" source="_IoIKa5F1EeqYh62qYTdhOg" target="_HPhFsJF3EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIwfpF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIwf5F1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIwgJF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIwgZF1EeqYh62qYTdhOg" points="[-73, -27, -229, 61]$[-73, -90, -229, -2]$[137, -90, -19, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIwgpF1EeqYh62qYTdhOg" id="(1.0,0.4090909090909091)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIwhJF1EeqYh62qYTdhOg" type="4001" element="_IoIJ4pF1EeqYh62qYTdhOg" source="_IoIKbpF1EeqYh62qYTdhOg" target="_JMoLQJF6EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIwhZF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIwhpF1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIwh5F1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIwiJF1EeqYh62qYTdhOg" points="[-58, 32, -7, -55]$[-58, 58, -7, -29]$[-50, 58, 1, -29]$[-50, 84, 1, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIwiZF1EeqYh62qYTdhOg" id="(1.0,0.4666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LN8-QJGEEeqYh62qYTdhOg" id="(0.43333333333333335,0.05)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIwi5F1EeqYh62qYTdhOg" type="4001" element="_IoIJ5ZF1EeqYh62qYTdhOg" source="_IoIKoZF1EeqYh62qYTdhOg" target="_IoIKpJF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIwjJF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIwjZF1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIwjpF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIwj5F1EeqYh62qYTdhOg" points="[-1, 33, 0, -56]$[-1, 68, 0, -21]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIwkJF1EeqYh62qYTdhOg" type="4001" element="_IoIJ6JF1EeqYh62qYTdhOg" source="_IoIKpJF1EeqYh62qYTdhOg" target="_IoIKlZF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIwkZF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIwkpF1EeqYh62qYTdhOg" x="4" y="-284"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIwk5F1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIwlJF1EeqYh62qYTdhOg" points="[0, -14, -320, 346]$[320, -14, 0, 346]$[320, -353, 0, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIwlZF1EeqYh62qYTdhOg" id="(1.0,0.813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIwlpF1EeqYh62qYTdhOg" id="(0.5348837209302325,0.7906976744186046)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIwnZF1EeqYh62qYTdhOg" type="4001" element="_IoIJ7pF1EeqYh62qYTdhOg" source="_IoIKdJF1EeqYh62qYTdhOg" target="_IoIKeJF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIwnpF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIwn5F1EeqYh62qYTdhOg" x="24" y="-17"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIwoJF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIwoZF1EeqYh62qYTdhOg" points="[0, 22, 3, -92]$[0, 78, 3, -36]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIwrpF1EeqYh62qYTdhOg" type="4001" element="_IoIJ95F1EeqYh62qYTdhOg" source="_IoIKe5F1EeqYh62qYTdhOg" target="_IoIKjZF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIwr5F1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIwsJF1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIwsZF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIwspF1EeqYh62qYTdhOg" points="[70, -1, -418, -1]$[473, -1, -15, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIwxZF1EeqYh62qYTdhOg" type="4001" element="_IoIKA5F1EeqYh62qYTdhOg" source="_IoIKV5F1EeqYh62qYTdhOg" target="_IoIKZZF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIwxpF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIwx5F1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIwyJF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIwyZF1EeqYh62qYTdhOg" points="[-54, -32, 0, 279]$[-54, -278, 0, 33]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIwypF1EeqYh62qYTdhOg" id="(1.0,0.5333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIwy5F1EeqYh62qYTdhOg" type="4001" element="_IoIKBpF1EeqYh62qYTdhOg" source="_IoIKt5F1EeqYh62qYTdhOg" target="_IoIKkZF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIwzJF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIwzZF1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIwzpF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIwz5F1EeqYh62qYTdhOg" points="[-83, -32, -3, 474]$[-83, -488, -3, 18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIw0JF1EeqYh62qYTdhOg" id="(1.0,0.4383561643835616)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIw0ZF1EeqYh62qYTdhOg" type="4001" element="_IoIKCZF1EeqYh62qYTdhOg" source="_IoIKpJF1EeqYh62qYTdhOg" target="_aKe54JGCEeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIw0pF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIw05F1EeqYh62qYTdhOg" x="-10" y="103"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIw1JF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIw1ZF1EeqYh62qYTdhOg" points="[-15, 7, 150, 252]$[-174, 7, -9, 252]$[-174, -243, -9, 2]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iNlr8JYoEeq2K99SrQ8DiQ" id="(0.627906976744186,0.8604651162790697)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIw1pF1EeqYh62qYTdhOg" type="4001" element="_IoIKDJF1EeqYh62qYTdhOg" source="_IoIKqJF1EeqYh62qYTdhOg" target="_IoIKq5F1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIw15F1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIw2JF1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIw2ZF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIw2pF1EeqYh62qYTdhOg" points="[-138, -1, 207, 0]$[-323, -1, 22, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIw25F1EeqYh62qYTdhOg" id="(1.0,0.52)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIw3JF1EeqYh62qYTdhOg" type="4001" element="_IoIKD5F1EeqYh62qYTdhOg" source="_IoIKq5F1EeqYh62qYTdhOg" target="_IoIKt5F1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIw3ZF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIw3pF1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIw35F1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIw4JF1EeqYh62qYTdhOg" points="[-22, 13, -186, -360]$[-22, 373, -186, 0]$[90, 373, -74, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIw4ZF1EeqYh62qYTdhOg" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIw55F1EeqYh62qYTdhOg" type="4001" element="_IoIKFZF1EeqYh62qYTdhOg" source="_IoIKkZF1EeqYh62qYTdhOg" target="_IoIKdJF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIw6JF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIw6ZF1EeqYh62qYTdhOg" x="-210" y="-8"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIw6pF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIw65F1EeqYh62qYTdhOg" points="[0, -12, -516, 3]$[510, -12, -6, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIw7JF1EeqYh62qYTdhOg" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIw7ZF1EeqYh62qYTdhOg" id="(0.20930232558139536,0.5116279069767442)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIw7pF1EeqYh62qYTdhOg" type="4001" element="_IoIKGJF1EeqYh62qYTdhOg" source="_IoIKdJF1EeqYh62qYTdhOg" target="_IoIKlZF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIw75F1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIw8JF1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIw8ZF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIw8pF1EeqYh62qYTdhOg" points="[0, -9, -166, 0]$[145, -9, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIw85F1EeqYh62qYTdhOg" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIw9JF1EeqYh62qYTdhOg" type="4001" element="_IoIKG5F1EeqYh62qYTdhOg" source="_IoIKlZF1EeqYh62qYTdhOg" target="_IoIKcZF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIw9ZF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIw9pF1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIw95F1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIw-JF1EeqYh62qYTdhOg" points="[-22, -28, -13, 399]$[-22, -413, -13, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIw-ZF1EeqYh62qYTdhOg" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IoIw-pF1EeqYh62qYTdhOg" id="(0.603448275862069,0.7586206896551724)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IoIw-5F1EeqYh62qYTdhOg" type="4001" element="_IoIKHpF1EeqYh62qYTdhOg" source="_IoIKWpF1EeqYh62qYTdhOg" target="_IoIKTZF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IoIw_JF1EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IoIw_ZF1EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IoIw_pF1EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IoIw_5F1EeqYh62qYTdhOg" points="[-1, 28, -155, -55]$[-1, 87, -155, 4]$[84, 87, -70, 4]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HQumoJF3EeqYh62qYTdhOg" type="4001" element="_HQpHEJF3EeqYh62qYTdhOg" source="_HPhFsJF3EeqYh62qYTdhOg" target="_ABZqcJF9EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HQwb0JF3EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HQwb0ZF3EeqYh62qYTdhOg" x="-4" y="17"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HQumoZF3EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HQumopF3EeqYh62qYTdhOg" points="[22, 0, -119, -18]$[135, 0, -6, -18]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_G3yREJYrEeq2K99SrQ8DiQ" id="(0.13953488372093023,0.9069767441860465)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QRUdYJF3EeqYh62qYTdhOg" type="4001" element="_QRA7YJF3EeqYh62qYTdhOg" source="_HPhFsJF3EeqYh62qYTdhOg" target="_aKe54JGCEeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QRUdY5F3EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QRVEcJF3EeqYh62qYTdhOg" x="-167" y="-14"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QRUdYZF3EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QRUdYpF3EeqYh62qYTdhOg" points="[-23, 9, -5, -484]$[-23, 477, -5, -16]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_QRXgsJF3EeqYh62qYTdhOg" id="(1.0,0.7441860465116279)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OXKPEJF9EeqYh62qYTdhOg" type="4001" element="_OWoDkJF9EeqYh62qYTdhOg" source="_ABZqcJF9EeqYh62qYTdhOg" target="_ISHfQ5GEEeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OXKPE5F9EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OXKPFJF9EeqYh62qYTdhOg" x="-8" y="-18"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OXKPEZF9EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OXKPEpF9EeqYh62qYTdhOg" points="[-1, -8, -21, -156]$[-1, 148, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OXMrUJF9EeqYh62qYTdhOg" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_f7bXEJF9EeqYh62qYTdhOg" type="4001" element="_f7awAJF9EeqYh62qYTdhOg" source="_f7VQcJF9EeqYh62qYTdhOg" target="_IoIKa5F1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_f7bXE5F9EeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_f7bXFJF9EeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_f7bXEZF9EeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_f7bXEpF9EeqYh62qYTdhOg" points="[4, -33, -1, 114]$[4, -114, -1, 33]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aKlAgJGCEeqYh62qYTdhOg" type="4001" element="_aKkZcJGCEeqYh62qYTdhOg" source="_aKe54JGCEeqYh62qYTdhOg" target="_IoIKqJF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aKlAg5GCEeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aKlAhJGCEeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aKlAgZGCEeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aKlAgpGCEeqYh62qYTdhOg" points="[-19, -2, 104, -2]$[-54, -2, 69, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ISLws5GEEeqYh62qYTdhOg" type="4001" element="_ISLwsJGEEeqYh62qYTdhOg" source="_ISHfQ5GEEeqYh62qYTdhOg" target="_ZjHhcJGOEeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ISMXwJGEEeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ISMXwZGEEeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ISLwtJGEEeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ISLwtZGEEeqYh62qYTdhOg" points="[-1, 20, -8, -80]$[-1, 68, -8, -32]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZjMZ8JGOEeqYh62qYTdhOg" type="4001" element="_ZjLy4JGOEeqYh62qYTdhOg" source="_ZjHhcJGOEeqYh62qYTdhOg" target="_IoIKoZF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZjMZ85GOEeqYh62qYTdhOg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZjMZ9JGOEeqYh62qYTdhOg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZjMZ8ZGOEeqYh62qYTdhOg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZjMZ8pGOEeqYh62qYTdhOg" points="[-1, 33, -14, -455]$[-1, 456, -14, -32]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nGX-oJOdEeqcrv5mpi41Dg" type="4001" element="_nGWwgJOdEeqcrv5mpi41Dg" source="_nGPbwJOdEeqcrv5mpi41Dg" target="_f7VQcJF9EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nGX-o5OdEeqcrv5mpi41Dg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nGX-pJOdEeqcrv5mpi41Dg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nGX-oZOdEeqcrv5mpi41Dg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nGX-opOdEeqcrv5mpi41Dg" points="[-3, -33, -4, 127]$[-3, -127, -4, 33]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PRdB0JOmEeqcrv5mpi41Dg" type="4001" element="_PRbzsJOmEeqcrv5mpi41Dg" source="_5jFDIJOgEeqcrv5mpi41Dg" target="_en_YEJPUEeqcrv5mpi41Dg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PRdo4JOmEeqcrv5mpi41Dg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PRdo4ZOmEeqcrv5mpi41Dg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PRdB0ZOmEeqcrv5mpi41Dg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PRdB0pOmEeqcrv5mpi41Dg" points="[-61, 27, 6, -1028]$[-61, 1022, 6, -33]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PRfeEJOmEeqcrv5mpi41Dg" id="(1.0,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_u5N5wJOmEeqcrv5mpi41Dg" type="4001" element="_u5NSsJOmEeqcrv5mpi41Dg" source="__ToTM5OlEeqcrv5mpi41Dg" target="_qHdvQJPYEeqcrv5mpi41Dg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_u5N5w5OmEeqcrv5mpi41Dg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_u5N5xJOmEeqcrv5mpi41Dg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_u5N5wZOmEeqcrv5mpi41Dg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_u5N5wpOmEeqcrv5mpi41Dg" points="[-64, -34, 217, 206]$[-64, -240, 217, 0]$[-259, -240, 22, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_u5Pu8JOmEeqcrv5mpi41Dg" id="(1.0,0.5396825396825397)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Bj4akJPSEeqcrv5mpi41Dg" type="4001" element="_BjfZAJPSEeqcrv5mpi41Dg" source="_IoIKkZF1EeqYh62qYTdhOg" target="_nGPbwJOdEeqcrv5mpi41Dg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Bj5BoJPSEeqcrv5mpi41Dg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Bj5BoZPSEeqcrv5mpi41Dg" x="-11" y="-14"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Bj4akZPSEeqcrv5mpi41Dg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Bj4akpPSEeqcrv5mpi41Dg" points="[-22, -27, 0, 110]$[-22, -104, 0, 33]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Bj8sAJPSEeqcrv5mpi41Dg" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_eoK-QJPUEeqcrv5mpi41Dg" type="4001" element="_eoKXMJPUEeqcrv5mpi41Dg" source="_en_YEJPUEeqcrv5mpi41Dg" target="_lzPd0JPUEeqcrv5mpi41Dg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_eoLlUpPUEeqcrv5mpi41Dg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_eoLlU5PUEeqcrv5mpi41Dg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_eoLlUJPUEeqcrv5mpi41Dg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_eoLlUZPUEeqcrv5mpi41Dg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lzWykJPUEeqcrv5mpi41Dg" type="4001" element="_lzWLgJPUEeqcrv5mpi41Dg" source="_lzPd0JPUEeqcrv5mpi41Dg" target="_XAWUcJPYEeqcrv5mpi41Dg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lzWyk5PUEeqcrv5mpi41Dg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lzWylJPUEeqcrv5mpi41Dg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lzWykZPUEeqcrv5mpi41Dg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lzWykpPUEeqcrv5mpi41Dg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XAcbEJPYEeqcrv5mpi41Dg" type="4001" element="_XAb0AJPYEeqcrv5mpi41Dg" source="_XAWUcJPYEeqcrv5mpi41Dg" target="__ToTM5OlEeqcrv5mpi41Dg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XAcbE5PYEeqcrv5mpi41Dg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XAcbFJPYEeqcrv5mpi41Dg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XAcbEZPYEeqcrv5mpi41Dg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XAcbEpPYEeqcrv5mpi41Dg" points="[5, 17, -318, -91]$[5, 108, -318, 0]$[260, 108, -63, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qHiAsJPYEeqcrv5mpi41Dg" type="4001" element="_qHhZoJPYEeqcrv5mpi41Dg" source="_qHdvQJPYEeqcrv5mpi41Dg" target="_IoIKV5F1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qHiAs5PYEeqcrv5mpi41Dg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qHiAtJPYEeqcrv5mpi41Dg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qHiAsZPYEeqcrv5mpi41Dg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qHiAspPYEeqcrv5mpi41Dg" points="[0, -21, 2, 704]$[0, -695, 2, 30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_21aBgJPYEeqcrv5mpi41Dg" type="4001" element="_201ZwJPYEeqcrv5mpi41Dg" source="_XAWUcJPYEeqcrv5mpi41Dg" target="_nw1kAJYmEeq2K99SrQ8DiQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_21aBg5PYEeqcrv5mpi41Dg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_21aokJPYEeqcrv5mpi41Dg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_21aBgZPYEeqcrv5mpi41Dg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_21aBgpPYEeqcrv5mpi41Dg" points="[0, -9, -133, -1]$[67, -9, -66, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_21b2sJPYEeqcrv5mpi41Dg" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Ib3V8JYKEeq2K99SrQ8DiQ" type="4001" element="_IbLZcJYKEeq2K99SrQ8DiQ" source="_IoIKeJF1EeqYh62qYTdhOg" target="_IoIKe5F1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ib5LIJYKEeq2K99SrQ8DiQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Ib5LIZYKEeq2K99SrQ8DiQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ib39AJYKEeq2K99SrQ8DiQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Ib39AZYKEeq2K99SrQ8DiQ" points="[-72, 41, 60, -365]$[-72, 379, 60, -27]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ib_RwJYKEeq2K99SrQ8DiQ" id="(1.0,0.4383561643835616)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ib_RwZYKEeq2K99SrQ8DiQ" id="(0.07971014492753623,0.391304347826087)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nw84wJYmEeq2K99SrQ8DiQ" type="4001" element="_nw8RsJYmEeq2K99SrQ8DiQ" source="_nw1kAJYmEeq2K99SrQ8DiQ" target="_qHdvQJPYEeqcrv5mpi41Dg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nw9f0JYmEeq2K99SrQ8DiQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nw9f0ZYmEeq2K99SrQ8DiQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nw84wZYmEeq2K99SrQ8DiQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nw84wpYmEeq2K99SrQ8DiQ" points="[-8, -25, 0, 105]$[-8, -108, 0, 22]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5QSgoJYqEeq2K99SrQ8DiQ" type="4001" element="_5QR5kJYqEeq2K99SrQ8DiQ" source="_IoIKcZF1EeqYh62qYTdhOg" target="_HPhFsJF3EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5QSgo5YqEeq2K99SrQ8DiQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5QSgpJYqEeq2K99SrQ8DiQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5QSgoZYqEeq2K99SrQ8DiQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5QSgopYqEeq2K99SrQ8DiQ" points="[-116, 0, 472, -38]$[-574, 0, 14, -38]$[-574, 38, 14, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5QU84JYqEeq2K99SrQ8DiQ" id="(1.0,0.46551724137931033)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5QU84ZYqEeq2K99SrQ8DiQ" id="(0.16279069767441862,0.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XK2acJYsEeq2K99SrQ8DiQ" type="4001" element="_XKf1IJYsEeq2K99SrQ8DiQ" source="_ABZqcJF9EeqYh62qYTdhOg" target="_IoIKbpF1EeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XK3BgJYsEeq2K99SrQ8DiQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XK3BgZYsEeq2K99SrQ8DiQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XK2acZYsEeq2K99SrQ8DiQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XK2acpYsEeq2K99SrQ8DiQ" points="[-3, -5, -158, 9]$[45, -5, -110, 9]$[45, -9, -110, 5]$[95, -9, -60, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_XK5dwJYsEeq2K99SrQ8DiQ" id="(1.0,0.5581395348837209)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dzrvoJYsEeq2K99SrQ8DiQ" type="4001" element="_dzrIkJYsEeq2K99SrQ8DiQ" source="_JMoLQJF6EeqYh62qYTdhOg" target="_ISHfQ5GEEeqYh62qYTdhOg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dzrvo5YsEeq2K99SrQ8DiQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dzsWsJYsEeq2K99SrQ8DiQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dzrvoZYsEeq2K99SrQ8DiQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dzrvopYsEeq2K99SrQ8DiQ" points="[-90, -8, 83, -3]$[-174, -20, -1, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dztk0JYsEeq2K99SrQ8DiQ" id="(1.0,0.6)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
