<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_XbxGMI4nEeq1tsXCfXZEaw" name="ST-Diagrama de Solucion Tecnica" version="1.0.0" author="Mireya" bonitaVersion="7.10.1" bonitaModelVersion="7.10.0-001" configId="ACED0005740010372E31302E302D303031372E31302E31">
    <elements xmi:type="process:Pool" xmi:id="_XbxGMY4nEeq1tsXCfXZEaw" name="Proceso de Solucion Tecnica" version="1.0.0">
      <elements xmi:type="process:Lane" xmi:id="_XbxGMo4nEeq1tsXCfXZEaw" name="Preventa" actor="_XbxGS44nEeq1tsXCfXZEaw">
        <elements xmi:type="process:StartEvent" xmi:id="_XbxGM44nEeq1tsXCfXZEaw" name="Inicio" outgoing="_PLbgUI4qEeqjr90pQBDU9w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XbxGNI4nEeq1tsXCfXZEaw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XbxGNY4nEeq1tsXCfXZEaw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XbxGNo4nEeq1tsXCfXZEaw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_QL3CkI4qEeqjr90pQBDU9w" name="¿Existen lideres asignados?" outgoing="_eF_bII4qEeqjr90pQBDU9w _OdtXUI4tEeqjr90pQBDU9w" incoming="_PLbgUI4qEeqjr90pQBDU9w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PJeYgI4qEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PJdxcI4qEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PJeYgY4qEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_vqWX0I4sEeqjr90pQBDU9w" name="Asignar Gerencia Operativa" outgoing="_fxIm8I4tEeqjr90pQBDU9w" incoming="_0v4NsI8dEeqql-eK1hC8eA" type="PARALLEL">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_eFV64o4qEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_eFV64Y4qEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_eFV6444qEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_eFV65I4qEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_eFV65Y4qEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_eFWh8I4qEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_eFWh8o4qEeqjr90pQBDU9w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_eFWh8Y4qEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_vqYNA44sEeqjr90pQBDU9w" name="Proceso de Asignacion de Gerencia Operativa" content="Proceso de Asignacion de Gerencia Operativa" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_vqYNBI4sEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Odk0cI4tEeqjr90pQBDU9w" name="Obtener lista de Arquitectos" outgoing="_fBJUcI4tEeqjr90pQBDU9w" incoming="_OdtXUI4tEeqjr90pQBDU9w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OdlbgY4tEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OdlbgI4tEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Odlbgo4tEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Odlbg44tEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_OdlbhI4tEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_OdlbhY4tEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Odlbh44tEeqjr90pQBDU9w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Odlbho4tEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_avGQcI4tEeqjr90pQBDU9w" name="Compuerta1" outgoing="_q2bgYI4tEeqjr90pQBDU9w" incoming="_fBJUcI4tEeqjr90pQBDU9w _fxIm8I4tEeqjr90pQBDU9w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_avG3gY4tEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_avG3gI4tEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_avG3go4tEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_mnwggI4tEeqjr90pQBDU9w" name="Notificar Revisión de proyecto" outgoing="_cpJKII8QEeqql-eK1hC8eA" incoming="_q2bgYI4tEeqjr90pQBDU9w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_mnxHkY4tEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_mnxHkI4tEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_mnxHko4tEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_YPMi0I8aEeqql-eK1hC8eA" name="Notificación de tarea" definitionId="email" event="ON_FINISH" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_YPMi0Y8aEeqql-eK1hC8eA" definitionId="email" version="1.1.0" modelVersion="7.10.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi0o8aEeqql-eK1hC8eA" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_YPMi048aEeqql-eK1hC8eA" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi1I8aEeqql-eK1hC8eA" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_YPMi1Y8aEeqql-eK1hC8eA" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi1o8aEeqql-eK1hC8eA" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_YPMi148aEeqql-eK1hC8eA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi2I8aEeqql-eK1hC8eA" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_YPMi2Y8aEeqql-eK1hC8eA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi2o8aEeqql-eK1hC8eA" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_YPMi248aEeqql-eK1hC8eA" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi3I8aEeqql-eK1hC8eA" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_YPMi3Y8aEeqql-eK1hC8eA" name="$$Dhst_23" content="$$Dhst_23" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi3o8aEeqql-eK1hC8eA" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_YPMi348aEeqql-eK1hC8eA" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi4I8aEeqql-eK1hC8eA" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_YPMi4Y8aEeqql-eK1hC8eA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi4o8aEeqql-eK1hC8eA" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_YPMi448aEeqql-eK1hC8eA" name="opacheco@hightech-corp.com" content="opacheco@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi5I8aEeqql-eK1hC8eA" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_YPMi5Y8aEeqql-eK1hC8eA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi5o8aEeqql-eK1hC8eA" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_YPMi548aEeqql-eK1hC8eA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi6I8aEeqql-eK1hC8eA" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_YPMi6Y8aEeqql-eK1hC8eA" name="Notificacion" content="Notificacion" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi6o8aEeqql-eK1hC8eA" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_YPMi648aEeqql-eK1hC8eA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi7I8aEeqql-eK1hC8eA" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_YPMi7Y8aEeqql-eK1hC8eA" name="&lt;pattern-expression>" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi7o8aEeqql-eK1hC8eA" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_YPMi748aEeqql-eK1hC8eA"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi8I8aEeqql-eK1hC8eA" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_YPMi8Y8aEeqql-eK1hC8eA" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi8o8aEeqql-eK1hC8eA" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_YPMi848aEeqql-eK1hC8eA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YPMi9I8aEeqql-eK1hC8eA" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_YPMi9Y8aEeqql-eK1hC8eA"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_mnxHk44tEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_mnxHlI4tEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_mnxHlY4tEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_mnxHl44tEeqjr90pQBDU9w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_mnxHlo4tEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_0vw48I8dEeqql-eK1hC8eA" name="Obtener lista de Preventa" outgoing="_0v4NsI8dEeqql-eK1hC8eA" incoming="_eF_bII4qEeqjr90pQBDU9w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0vxgAY8dEeqql-eK1hC8eA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0vxgAI8dEeqql-eK1hC8eA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0vxgAo8dEeqql-eK1hC8eA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0vxgA48dEeqql-eK1hC8eA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0vxgBI8dEeqql-eK1hC8eA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0vxgBY8dEeqql-eK1hC8eA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0vxgB48dEeqql-eK1hC8eA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0vxgBo8dEeqql-eK1hC8eA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_6JzgoI4pEeqjr90pQBDU9w" name="Arquitectura">
        <elements xmi:type="process:Task" xmi:id="_XbxGN44nEeq1tsXCfXZEaw" name="Revisar Proyecto Asignado " outgoing="_v3VsII5GEeqjr90pQBDU9w" incoming="_cpJKII8QEeqql-eK1hC8eA" type="PARALLEL" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XbxGOI4nEeq1tsXCfXZEaw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XbxGOY4nEeq1tsXCfXZEaw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XbxGOo4nEeq1tsXCfXZEaw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XbxGO44nEeq1tsXCfXZEaw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XbxGPI4nEeq1tsXCfXZEaw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XbxGPY4nEeq1tsXCfXZEaw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XbxGPo4nEeq1tsXCfXZEaw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XbxGP44nEeq1tsXCfXZEaw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_XbxGQI4nEeq1tsXCfXZEaw">
            <targetForm xmi:type="expression:Expression" xmi:id="_XbxGQY4nEeq1tsXCfXZEaw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_XbxGQo4nEeq1tsXCfXZEaw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_XbxGQ44nEeq1tsXCfXZEaw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_VWjXEI4wEeqjr90pQBDU9w" name="Solicitar reunión con el cliente" outgoing="_4KHskI5EEeqjr90pQBDU9w" incoming="_v3VsII5GEeqjr90pQBDU9w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VWjXEo4wEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VWjXEY4wEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VWjXE44wEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_4xNcgI8aEeqql-eK1hC8eA" name="Notificación de Tarea" definitionId="email" event="ON_FINISH" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_4xNcgY8aEeqql-eK1hC8eA" definitionId="email" version="1.1.0" modelVersion="7.10.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNcgo8aEeqql-eK1hC8eA" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_4xNcg48aEeqql-eK1hC8eA" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNchI8aEeqql-eK1hC8eA" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_4xNchY8aEeqql-eK1hC8eA" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNcho8aEeqql-eK1hC8eA" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_4xNch48aEeqql-eK1hC8eA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNciI8aEeqql-eK1hC8eA" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_4xNciY8aEeqql-eK1hC8eA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNcio8aEeqql-eK1hC8eA" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_4xNci48aEeqql-eK1hC8eA" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNcjI8aEeqql-eK1hC8eA" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_4xNcjY8aEeqql-eK1hC8eA" name="$$Dhst_23" content="$$Dhst_23" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNcjo8aEeqql-eK1hC8eA" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_4xNcj48aEeqql-eK1hC8eA" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNckI8aEeqql-eK1hC8eA" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_4xNckY8aEeqql-eK1hC8eA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNcko8aEeqql-eK1hC8eA" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_4xNck48aEeqql-eK1hC8eA" name="opacheco@hightech-corp.com" content="opacheco@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNclI8aEeqql-eK1hC8eA" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_4xNclY8aEeqql-eK1hC8eA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNclo8aEeqql-eK1hC8eA" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_4xNcl48aEeqql-eK1hC8eA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNcmI8aEeqql-eK1hC8eA" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_4xNcmY8aEeqql-eK1hC8eA" name="Notificación de Tarea" content="Notificación de Tarea" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNcmo8aEeqql-eK1hC8eA" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_4xNcm48aEeqql-eK1hC8eA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNcnI8aEeqql-eK1hC8eA" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_4xNcnY8aEeqql-eK1hC8eA" name="&lt;pattern-expression>" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNcno8aEeqql-eK1hC8eA" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_4xNcn48aEeqql-eK1hC8eA"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNcoI8aEeqql-eK1hC8eA" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_4xNcoY8aEeqql-eK1hC8eA" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNcoo8aEeqql-eK1hC8eA" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_4xNco48aEeqql-eK1hC8eA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4xNcpI8aEeqql-eK1hC8eA" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_4xNcpY8aEeqql-eK1hC8eA"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_VWjXFI4wEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_VWjXFY4wEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VWjXFo4wEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_VWj-II4wEeqjr90pQBDU9w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_VWjXF44wEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_1X5nII5FEeqjr90pQBDU9w" name="Elaboración SDD" outgoing="_WEq-UI5REeqjr90pQBDU9w" incoming="_sfWYYI8REeqql-eK1hC8eA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1A3AIo5FEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1A3AIY5FEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1A3nMI5FEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_1A3nMY5FEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_1A3nMo5FEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_1A3nM45FEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_1A3nNY5FEeqjr90pQBDU9w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_1A3nNI5FEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_1X5nKo5FEeqjr90pQBDU9w">
            <targetForm xmi:type="expression:Expression" xmi:id="_1X5nK45FEeqjr90pQBDU9w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_1X5nKY5FEeqjr90pQBDU9w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_1X5nLI5FEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Q7Ue4I5REeqjr90pQBDU9w" name="Notificación de Revisión" outgoing="_iUqJQI5REeqjr90pQBDU9w" incoming="_WEq-UI5REeqjr90pQBDU9w _PIZTQI5SEeqjr90pQBDU9w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Q7VtAY5REeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Q7VtAI5REeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Q7VtAo5REeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_cOd_UI8bEeqql-eK1hC8eA" name="Notificación de Tarea" definitionId="email" event="ON_FINISH" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_cOd_UY8bEeqql-eK1hC8eA" definitionId="email" version="1.1.0" modelVersion="7.10.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_Uo8bEeqql-eK1hC8eA" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_cOd_U48bEeqql-eK1hC8eA" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_VI8bEeqql-eK1hC8eA" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_cOd_VY8bEeqql-eK1hC8eA" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_Vo8bEeqql-eK1hC8eA" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_cOd_V48bEeqql-eK1hC8eA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_WI8bEeqql-eK1hC8eA" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_cOd_WY8bEeqql-eK1hC8eA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_Wo8bEeqql-eK1hC8eA" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_cOd_W48bEeqql-eK1hC8eA" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_XI8bEeqql-eK1hC8eA" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_cOd_XY8bEeqql-eK1hC8eA" name="$$Dhst_23" content="$$Dhst_23" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_Xo8bEeqql-eK1hC8eA" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_cOd_X48bEeqql-eK1hC8eA" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_YI8bEeqql-eK1hC8eA" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_cOd_YY8bEeqql-eK1hC8eA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_Yo8bEeqql-eK1hC8eA" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_cOd_Y48bEeqql-eK1hC8eA" name="opacheco@hightech-corp.com" content="opacheco@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_ZI8bEeqql-eK1hC8eA" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_cOd_ZY8bEeqql-eK1hC8eA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_Zo8bEeqql-eK1hC8eA" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_cOd_Z48bEeqql-eK1hC8eA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_aI8bEeqql-eK1hC8eA" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_cOd_aY8bEeqql-eK1hC8eA" name="Notificación de Tarea" content="Notificación de Tarea" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_ao8bEeqql-eK1hC8eA" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_cOd_a48bEeqql-eK1hC8eA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_bI8bEeqql-eK1hC8eA" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_cOd_bY8bEeqql-eK1hC8eA" name="&lt;pattern-expression>" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_bo8bEeqql-eK1hC8eA" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_cOd_b48bEeqql-eK1hC8eA"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_cI8bEeqql-eK1hC8eA" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_cOd_cY8bEeqql-eK1hC8eA" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_co8bEeqql-eK1hC8eA" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_cOd_c48bEeqql-eK1hC8eA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_cOd_dI8bEeqql-eK1hC8eA" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_cOd_dY8bEeqql-eK1hC8eA"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Q7VtA45REeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Q7VtBI5REeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Q7VtBY5REeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Q7VtB45REeqjr90pQBDU9w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Q7VtBo5REeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_4zREUI5REeqjr90pQBDU9w" name="Modificación SDD" outgoing="_PIZTQI5SEeqjr90pQBDU9w" incoming="_AMq9AI5hEeqjr90pQBDU9w _IOKMUI8TEeqql-eK1hC8eA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4zREUo5REeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4zREUY5REeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4zREU45REeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4zREVI5REeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4zREVY5REeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4zREVo5REeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4zREWI5REeqjr90pQBDU9w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4zREV45REeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_4zREWo5REeqjr90pQBDU9w">
            <targetForm xmi:type="expression:Expression" xmi:id="_4zREW45REeqjr90pQBDU9w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_4zREWY5REeqjr90pQBDU9w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_4zREXI5REeqjr90pQBDU9w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_I8u64I5VEeqjr90pQBDU9w" name="¿Esta Aprobado por el Cliente?" outgoing="_cWoc4I5XEeqjr90pQBDU9w _G756QI8TEeqql-eK1hC8eA" incoming="_JDMzYI8SEeqql-eK1hC8eA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_H7an0o5VEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_H7an0Y5VEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_H7an045VEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_eQKxYI5XEeqjr90pQBDU9w" name="Entregar versión preliminar o definitiva SDD" outgoing="_GgUbcI5YEeqjr90pQBDU9w" incoming="_cWoc4I5XEeqjr90pQBDU9w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_cWkLcY5XEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_cWkLcI5XEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_cWkLco5XEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_cWkLc45XEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_cWkLdI5XEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_cWkLdY5XEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_cWkLd45XEeqjr90pQBDU9w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_cWkLdo5XEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_eQLYeY5XEeqjr90pQBDU9w">
            <targetForm xmi:type="expression:Expression" xmi:id="_eQLYeo5XEeqjr90pQBDU9w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_eQLYeI5XEeqjr90pQBDU9w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_eQLYe45XEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_GgO74I5YEeqjr90pQBDU9w" name="Notificación entrega SDD" outgoing="_41CoII5gEeqjr90pQBDU9w" incoming="_0E1ogI5gEeqjr90pQBDU9w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GgPi8Y5YEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GgPi8I5YEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GgPi8o5YEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_GgPi845YEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_GgPi9I5YEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GgPi9Y5YEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_GgPi945YEeqjr90pQBDU9w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_GgPi9o5YEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_L0rRAI5YEeqjr90pQBDU9w" name="Fin proceso" incoming="_-2AFAI5gEeqjr90pQBDU9w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_L0rRAo5YEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_L0rRAY5YEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_L0rRA45YEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kR8pcI5eEeqjr90pQBDU9w" name="Consulta si desea modificar SDD" outgoing="_6kGyAI5gEeqjr90pQBDU9w" incoming="_zrIvEI5gEeqjr90pQBDU9w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kR93kY5eEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kR93kI5eEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kR93ko5eEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kR93k45eEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kR93lI5eEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kR93lY5eEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kR93l45eEeqjr90pQBDU9w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kR93lo5eEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kR93mY5eEeqjr90pQBDU9w">
            <targetForm xmi:type="expression:Expression" xmi:id="_kR93mo5eEeqjr90pQBDU9w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kR93mI5eEeqjr90pQBDU9w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kR-eoI5eEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_r77SkI5eEeqjr90pQBDU9w" name="¿ Modificar SDD?" outgoing="_-2AFAI5gEeqjr90pQBDU9w _AMq9AI5hEeqjr90pQBDU9w" incoming="_6kGyAI5gEeqjr90pQBDU9w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_r77Sko5eEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_r77SkY5eEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_r77Sk45eEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_qseyAI5gEeqjr90pQBDU9w" name="Compuerta3" outgoing="_zrIvEI5gEeqjr90pQBDU9w _0E1ogI5gEeqjr90pQBDU9w" incoming="_GgUbcI5YEeqjr90pQBDU9w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qsfZEY5gEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qsfZEI5gEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qsfZEo5gEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_40-WsI5gEeqjr90pQBDU9w" name="Fin notificación" incoming="_41CoII5gEeqjr90pQBDU9w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_40-Wso5gEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_40-WsY5gEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_40-Ws45gEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_sfLZQI8REeqql-eK1hC8eA" name="¿Existe SDD?" outgoing="_sfWYYI8REeqql-eK1hC8eA _JDMzYI8SEeqql-eK1hC8eA" incoming="_fck7EI8QEeqql-eK1hC8eA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sfMAUY8REeqql-eK1hC8eA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sfMAUI8REeqql-eK1hC8eA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sfMAUo8REeqql-eK1hC8eA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_EkglEI8TEeqql-eK1hC8eA" name="Compuerta5" outgoing="_IOKMUI8TEeqql-eK1hC8eA" incoming="_2QdJUI5REeqjr90pQBDU9w _G756QI8TEeqql-eK1hC8eA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EkglEo8TEeqql-eK1hC8eA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EkglEY8TEeqql-eK1hC8eA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EkhMII8TEeqql-eK1hC8eA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_Aqat8I4qEeqjr90pQBDU9w" name="Comité Arquitectura">
        <elements xmi:type="process:Task" xmi:id="_aGE-QI5REeqjr90pQBDU9w" name="Revisión SDD" outgoing="_tPzBII5REeqjr90pQBDU9w" incoming="_iUqJQI5REeqjr90pQBDU9w" type="PARALLEL" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_aGFlUY5REeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_aGFlUI5REeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_aGFlUo5REeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_aGFlU45REeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_aGFlVI5REeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_aGFlVY5REeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_aGFlV45REeqjr90pQBDU9w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_aGFlVo5REeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_aGGMYY5REeqjr90pQBDU9w">
            <targetForm xmi:type="expression:Expression" xmi:id="_aGGMYo5REeqjr90pQBDU9w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_aGGMYI5REeqjr90pQBDU9w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_aGGMY45REeqjr90pQBDU9w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_tiq50I5REeqjr90pQBDU9w" name="¿Comité Presenta Observaciones?" outgoing="_2QdJUI5REeqjr90pQBDU9w _eWgOYI8REeqql-eK1hC8eA" incoming="_tPzBII5REeqjr90pQBDU9w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tPrsYI5REeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tPrFUI5REeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tPrsYY5REeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_eV5KYI8REeqql-eK1hC8eA" name="Notificación de Solicitud de Reunión" outgoing="_e9DRAI8REeqql-eK1hC8eA" incoming="_eWgOYI8REeqql-eK1hC8eA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_eWXEcY8REeqql-eK1hC8eA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_eWXEcI8REeqql-eK1hC8eA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_eWXEco8REeqql-eK1hC8eA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_-r704I8iEeqql-eK1hC8eA" name="Notificación de Tarea" definitionId="email" event="ON_FINISH" definitionVersion="1.1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_-r704Y8iEeqql-eK1hC8eA" definitionId="email" version="1.1.0" modelVersion="7.10.0-001">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r704o8iEeqql-eK1hC8eA" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_-r70448iEeqql-eK1hC8eA" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r705I8iEeqql-eK1hC8eA" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_-r705Y8iEeqql-eK1hC8eA" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r705o8iEeqql-eK1hC8eA" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_-r70548iEeqql-eK1hC8eA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r706I8iEeqql-eK1hC8eA" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_-r706Y8iEeqql-eK1hC8eA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r706o8iEeqql-eK1hC8eA" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_-r70648iEeqql-eK1hC8eA" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r707I8iEeqql-eK1hC8eA" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_-r707Y8iEeqql-eK1hC8eA" name="$$Dhst_23" content="$$Dhst_23" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r707o8iEeqql-eK1hC8eA" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_-r70748iEeqql-eK1hC8eA" name="mmunoz@hightech-corp.com" content="mmunoz@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r708I8iEeqql-eK1hC8eA" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_-r708Y8iEeqql-eK1hC8eA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r708o8iEeqql-eK1hC8eA" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_-r70848iEeqql-eK1hC8eA" name="opacheco@hightech-corp.com" content="opacheco@hightech-corp.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r709I8iEeqql-eK1hC8eA" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_-r709Y8iEeqql-eK1hC8eA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r709o8iEeqql-eK1hC8eA" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_-r70948iEeqql-eK1hC8eA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r70-I8iEeqql-eK1hC8eA" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_-r70-Y8iEeqql-eK1hC8eA" name="Notificación de Tarea" content="Notificación de Tarea" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r70-o8iEeqql-eK1hC8eA" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_-r70-48iEeqql-eK1hC8eA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r70_I8iEeqql-eK1hC8eA" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_-r70_Y8iEeqql-eK1hC8eA" name="&lt;pattern-expression>" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r70_o8iEeqql-eK1hC8eA" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_-r70_48iEeqql-eK1hC8eA"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r71AI8iEeqql-eK1hC8eA" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_-r71AY8iEeqql-eK1hC8eA" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r71Ao8iEeqql-eK1hC8eA" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_-r71A48iEeqql-eK1hC8eA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-r71BI8iEeqql-eK1hC8eA" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_-r71BY8iEeqql-eK1hC8eA"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_eWXEc48REeqql-eK1hC8eA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_eWXEdI8REeqql-eK1hC8eA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_eWXEdY8REeqql-eK1hC8eA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_eWXrgI8REeqql-eK1hC8eA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_eWXEdo8REeqql-eK1hC8eA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_QzEekI8REeqql-eK1hC8eA" name="Compuerta4" outgoing="_i1AaAI8REeqql-eK1hC8eA" incoming="_4KHskI5EEeqjr90pQBDU9w _e9DRAI8REeqql-eK1hC8eA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QzFFoY8REeqql-eK1hC8eA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QzFFoI8REeqql-eK1hC8eA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QzFFoo8REeqql-eK1hC8eA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_HcYJ8I4qEeqjr90pQBDU9w" name="PMO">
        <elements xmi:type="process:CallActivity" xmi:id="_mgg-UI5UEeqjr90pQBDU9w" name="Gestionar reunión cliente Doc Requerimiento" outgoing="_fck7EI8QEeqql-eK1hC8eA" incoming="_i1AaAI8REeqql-eK1hC8eA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ydTTsY5EEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ydTTsI5EEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ydTTso5EEeqjr90pQBDU9w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ydTTs45EEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ydTTtI5EEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ydTTtY5EEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ydTTt45EEeqjr90pQBDU9w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ydTTto5EEeqjr90pQBDU9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_mghlY45UEeqjr90pQBDU9w" name="ST-Proceso de Gestion de Reunion Cliente" content="ST-Proceso de Gestion de Reunion Cliente" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_mghlZI5UEeqjr90pQBDU9w" name="1.0.0" content="1.0.0" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_XbxGRI4nEeq1tsXCfXZEaw">
        <targetForm xmi:type="expression:Expression" xmi:id="_XbxGRY4nEeq1tsXCfXZEaw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_XbxGRo4nEeq1tsXCfXZEaw">
        <targetForm xmi:type="expression:Expression" xmi:id="_XbxGR44nEeq1tsXCfXZEaw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PLbgUI4qEeqjr90pQBDU9w" target="_QL3CkI4qEeqjr90pQBDU9w" source="_XbxGM44nEeq1tsXCfXZEaw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PLcHYI4qEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_PLcucI4qEeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_eF_bII4qEeqjr90pQBDU9w" name="No" target="_0vw48I8dEeqql-eK1hC8eA" source="_QL3CkI4qEeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_eF_bIY4qEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_eF_bIo4qEeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OdtXUI4tEeqjr90pQBDU9w" name="Si" target="_Odk0cI4tEeqjr90pQBDU9w" source="_QL3CkI4qEeqjr90pQBDU9w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OdtXUY4tEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_OdtXUo4tEeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fBJUcI4tEeqjr90pQBDU9w" target="_avGQcI4tEeqjr90pQBDU9w" source="_Odk0cI4tEeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fBJUcY4tEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_fBJUco4tEeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fxIm8I4tEeqjr90pQBDU9w" target="_avGQcI4tEeqjr90pQBDU9w" source="_vqWX0I4sEeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fxIm8Y4tEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_fxIm8o4tEeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_q2bgYI4tEeqjr90pQBDU9w" target="_mnwggI4tEeqjr90pQBDU9w" source="_avGQcI4tEeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_q2bgYY4tEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_q2cHcI4tEeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4KHskI5EEeqjr90pQBDU9w" target="_QzEekI8REeqql-eK1hC8eA" source="_VWjXEI4wEeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4KIToI5EEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_4KIToY5EEeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_v3VsII5GEeqjr90pQBDU9w" target="_VWjXEI4wEeqjr90pQBDU9w" source="_XbxGN44nEeq1tsXCfXZEaw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_v3VsIY5GEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_v3VsIo5GEeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WEq-UI5REeqjr90pQBDU9w" target="_Q7Ue4I5REeqjr90pQBDU9w" source="_1X5nII5FEeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WEq-UY5REeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_WEq-Uo5REeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iUqJQI5REeqjr90pQBDU9w" target="_aGE-QI5REeqjr90pQBDU9w" source="_Q7Ue4I5REeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_iUqJQY5REeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_iUqJQo5REeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tPzBII5REeqjr90pQBDU9w" target="_tiq50I5REeqjr90pQBDU9w" source="_aGE-QI5REeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tPzBIY5REeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_tPzBIo5REeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2QdJUI5REeqjr90pQBDU9w" name="Si" target="_EkglEI8TEeqql-eK1hC8eA" source="_tiq50I5REeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2QdJUY5REeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_2QdJUo5REeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PIZTQI5SEeqjr90pQBDU9w" target="_Q7Ue4I5REeqjr90pQBDU9w" source="_4zREUI5REeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PIZ6UI5SEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_PIZ6UY5SEeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cWoc4I5XEeqjr90pQBDU9w" name="Si" target="_eQKxYI5XEeqjr90pQBDU9w" source="_I8u64I5VEeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cWoc4Y5XEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_cWoc4o5XEeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GgUbcI5YEeqjr90pQBDU9w" target="_qseyAI5gEeqjr90pQBDU9w" source="_eQKxYI5XEeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GgUbcY5YEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_GgUbco5YEeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zrIvEI5gEeqjr90pQBDU9w" target="_kR8pcI5eEeqjr90pQBDU9w" source="_qseyAI5gEeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zrJWII5gEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_zrJWIY5gEeqjr90pQBDU9w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0E1ogI5gEeqjr90pQBDU9w" target="_GgO74I5YEeqjr90pQBDU9w" source="_qseyAI5gEeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0E1ogY5gEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_0E1ogo5gEeqjr90pQBDU9w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_41CoII5gEeqjr90pQBDU9w" target="_40-WsI5gEeqjr90pQBDU9w" source="_GgO74I5YEeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_41CoIY5gEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_41CoIo5gEeqjr90pQBDU9w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6kGyAI5gEeqjr90pQBDU9w" target="_r77SkI5eEeqjr90pQBDU9w" source="_kR8pcI5eEeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6kGyAY5gEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_6kGyAo5gEeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-2AFAI5gEeqjr90pQBDU9w" name="No" target="_L0rRAI5YEeqjr90pQBDU9w" source="_r77SkI5eEeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-2AFAY5gEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_-2AFAo5gEeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AMq9AI5hEeqjr90pQBDU9w" name="Si" target="_4zREUI5REeqjr90pQBDU9w" source="_r77SkI5eEeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AMq9AY5hEeqjr90pQBDU9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_AMq9Ao5hEeqjr90pQBDU9w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cpJKII8QEeqql-eK1hC8eA" target="_XbxGN44nEeq1tsXCfXZEaw" source="_mnwggI4tEeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cpJKIY8QEeqql-eK1hC8eA"/>
        <condition xmi:type="expression:Expression" xmi:id="_cpJKIo8QEeqql-eK1hC8eA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fck7EI8QEeqql-eK1hC8eA" target="_sfLZQI8REeqql-eK1hC8eA" source="_mgg-UI5UEeqjr90pQBDU9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fck7EY8QEeqql-eK1hC8eA"/>
        <condition xmi:type="expression:Expression" xmi:id="_fcliII8QEeqql-eK1hC8eA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_eWgOYI8REeqql-eK1hC8eA" name="No" target="_eV5KYI8REeqql-eK1hC8eA" source="_tiq50I5REeqjr90pQBDU9w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_eWgOYY8REeqql-eK1hC8eA"/>
        <condition xmi:type="expression:Expression" xmi:id="_eWgOYo8REeqql-eK1hC8eA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_e9DRAI8REeqql-eK1hC8eA" target="_QzEekI8REeqql-eK1hC8eA" source="_eV5KYI8REeqql-eK1hC8eA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_e9DRAY8REeqql-eK1hC8eA"/>
        <condition xmi:type="expression:Expression" xmi:id="_e9DRAo8REeqql-eK1hC8eA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_i1AaAI8REeqql-eK1hC8eA" target="_mgg-UI5UEeqjr90pQBDU9w" source="_QzEekI8REeqql-eK1hC8eA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_i1AaAY8REeqql-eK1hC8eA"/>
        <condition xmi:type="expression:Expression" xmi:id="_i1AaAo8REeqql-eK1hC8eA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sfWYYI8REeqql-eK1hC8eA" name="No" target="_1X5nII5FEeqjr90pQBDU9w" source="_sfLZQI8REeqql-eK1hC8eA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sfW_cI8REeqql-eK1hC8eA"/>
        <condition xmi:type="expression:Expression" xmi:id="_sfW_cY8REeqql-eK1hC8eA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JDMzYI8SEeqql-eK1hC8eA" name="Si" target="_I8u64I5VEeqjr90pQBDU9w" source="_sfLZQI8REeqql-eK1hC8eA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JDMzYY8SEeqql-eK1hC8eA"/>
        <condition xmi:type="expression:Expression" xmi:id="_JDMzYo8SEeqql-eK1hC8eA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_G756QI8TEeqql-eK1hC8eA" name="No" target="_EkglEI8TEeqql-eK1hC8eA" source="_I8u64I5VEeqjr90pQBDU9w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_G756QY8TEeqql-eK1hC8eA"/>
        <condition xmi:type="expression:Expression" xmi:id="_G756Qo8TEeqql-eK1hC8eA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IOKMUI8TEeqql-eK1hC8eA" target="_4zREUI5REeqjr90pQBDU9w" source="_EkglEI8TEeqql-eK1hC8eA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IOKMUY8TEeqql-eK1hC8eA"/>
        <condition xmi:type="expression:Expression" xmi:id="_IOKzYI8TEeqql-eK1hC8eA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0v4NsI8dEeqql-eK1hC8eA" target="_vqWX0I4sEeqjr90pQBDU9w" source="_0vw48I8dEeqql-eK1hC8eA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0v40wI8dEeqql-eK1hC8eA"/>
        <condition xmi:type="expression:Expression" xmi:id="_0v40wY8dEeqql-eK1hC8eA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_XbxGS44nEeq1tsXCfXZEaw" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_XbxGTI4nEeq1tsXCfXZEaw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XbxGTY4nEeq1tsXCfXZEaw">
        <name xmi:type="expression:Expression" xmi:id="_XbxGTo4nEeq1tsXCfXZEaw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XbxGT44nEeq1tsXCfXZEaw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XbxGUI4nEeq1tsXCfXZEaw">
        <name xmi:type="expression:Expression" xmi:id="_XbxGUY4nEeq1tsXCfXZEaw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XbxGUo4nEeq1tsXCfXZEaw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XbxGU44nEeq1tsXCfXZEaw">
        <name xmi:type="expression:Expression" xmi:id="_XbxGVI4nEeq1tsXCfXZEaw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XbxGVY4nEeq1tsXCfXZEaw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XbxGVo4nEeq1tsXCfXZEaw">
        <name xmi:type="expression:Expression" xmi:id="_XbxGV44nEeq1tsXCfXZEaw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XbxGWI4nEeq1tsXCfXZEaw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XbxGWY4nEeq1tsXCfXZEaw">
        <name xmi:type="expression:Expression" xmi:id="_XbxGWo4nEeq1tsXCfXZEaw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XbxGW44nEeq1tsXCfXZEaw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_XbxGXI4nEeq1tsXCfXZEaw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_XbxGXY4nEeq1tsXCfXZEaw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_XbxGXo4nEeq1tsXCfXZEaw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_XbxGX44nEeq1tsXCfXZEaw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_XbxGYI4nEeq1tsXCfXZEaw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_XbxtQI4nEeq1tsXCfXZEaw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_XbxtQY4nEeq1tsXCfXZEaw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_XbxtQo4nEeq1tsXCfXZEaw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_XbxtQ44nEeq1tsXCfXZEaw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_XbxtRI4nEeq1tsXCfXZEaw" type="Process" element="_XbxGMI4nEeq1tsXCfXZEaw" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_XbxtRY4nEeq1tsXCfXZEaw" type="2007" element="_XbxGMY4nEeq1tsXCfXZEaw">
      <children xmi:type="notation:DecorationNode" xmi:id="_XbxtRo4nEeq1tsXCfXZEaw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_XbxtR44nEeq1tsXCfXZEaw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_XbxtSI4nEeq1tsXCfXZEaw" type="3007" element="_XbxGMo4nEeq1tsXCfXZEaw">
          <children xmi:type="notation:DecorationNode" xmi:id="_XbxtSY4nEeq1tsXCfXZEaw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_XbxtSo4nEeq1tsXCfXZEaw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_XbxtTo4nEeq1tsXCfXZEaw" type="3002" element="_XbxGM44nEeq1tsXCfXZEaw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_XbxtT44nEeq1tsXCfXZEaw" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_XbxtUI4nEeq1tsXCfXZEaw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XbxtUY4nEeq1tsXCfXZEaw" x="42" y="41"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QL3po44qEeqjr90pQBDU9w" type="3008" element="_QL3CkI4qEeqjr90pQBDU9w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_QL4QsI4qEeqjr90pQBDU9w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_QL4QsY4qEeqjr90pQBDU9w" x="-12" y="-58"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QL3ppI4qEeqjr90pQBDU9w" x="183" y="34" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vqY0EI4sEeqjr90pQBDU9w" type="3063" element="_vqWX0I4sEeqjr90pQBDU9w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_vqY0Eo4sEeqjr90pQBDU9w" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vqY0EY4sEeqjr90pQBDU9w" x="289" y="194" width="140" height="71"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OdmpoI4tEeqjr90pQBDU9w" type="3027" element="_Odk0cI4tEeqjr90pQBDU9w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_OdnQsI4tEeqjr90pQBDU9w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OdmpoY4tEeqjr90pQBDU9w" x="441" y="26" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_avHekI4tEeqjr90pQBDU9w" type="3008" element="_avGQcI4tEeqjr90pQBDU9w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_avHeko4tEeqjr90pQBDU9w" visible="false" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_avHek44tEeqjr90pQBDU9w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_avHekY4tEeqjr90pQBDU9w" x="479" y="208"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_mnyVsI4tEeqjr90pQBDU9w" type="3027" element="_mnwggI4tEeqjr90pQBDU9w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_mny8wI4tEeqjr90pQBDU9w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mnyVsY4tEeqjr90pQBDU9w" x="74" y="274" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0vyuII8dEeqql-eK1hC8eA" type="3027" element="_0vw48I8dEeqql-eK1hC8eA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0vyuIo8dEeqql-eK1hC8eA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0vyuIY8dEeqql-eK1hC8eA" x="149" y="118" width="112" height="56"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_XbxtUo4nEeq1tsXCfXZEaw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_XbxtU44nEeq1tsXCfXZEaw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_XbxtVI4nEeq1tsXCfXZEaw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_XbxtVY4nEeq1tsXCfXZEaw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XbxtVo4nEeq1tsXCfXZEaw" x="23" y="10" width="1522" height="389"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_6Pyz4I4pEeqjr90pQBDU9w" type="3007" element="_6JzgoI4pEeqjr90pQBDU9w">
          <children xmi:type="notation:DecorationNode" xmi:id="_6P0CAI4pEeqjr90pQBDU9w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_6P0CAY4pEeqjr90pQBDU9w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_XbxtS44nEeq1tsXCfXZEaw" type="3005" element="_XbxGN44nEeq1tsXCfXZEaw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_XbxtTI4nEeq1tsXCfXZEaw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XbxtTY4nEeq1tsXCfXZEaw" x="67" y="37" width="133" height="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_VWklMI4wEeqjr90pQBDU9w" type="3027" element="_VWjXEI4wEeqjr90pQBDU9w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_VWlMQI4wEeqjr90pQBDU9w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VWklMY4wEeqjr90pQBDU9w" x="70" y="201" width="127" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1X6OMI5FEeqjr90pQBDU9w" type="3005" element="_1X5nII5FEeqjr90pQBDU9w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_1X6OMo5FEeqjr90pQBDU9w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1X6OMY5FEeqjr90pQBDU9w" x="262" y="37" width="132" height="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Q7XiMI5REeqjr90pQBDU9w" type="3027" element="_Q7Ue4I5REeqjr90pQBDU9w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Q7XiMo5REeqjr90pQBDU9w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q7XiMY5REeqjr90pQBDU9w" x="479" y="40" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4zRrYI5REeqjr90pQBDU9w" type="3005" element="_4zREUI5REeqjr90pQBDU9w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4zSScI5REeqjr90pQBDU9w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4zRrYY5REeqjr90pQBDU9w" x="671" y="41" width="116" height="58"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_I8vh845VEeqjr90pQBDU9w" type="3008" element="_I8u64I5VEeqjr90pQBDU9w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_I8vh9Y5VEeqjr90pQBDU9w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_I8vh9o5VEeqjr90pQBDU9w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_I8vh9I5VEeqjr90pQBDU9w" x="612" y="263" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eQLYfI5XEeqjr90pQBDU9w" type="3005" element="_eQKxYI5XEeqjr90pQBDU9w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_eQL_gI5XEeqjr90pQBDU9w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eQLYfY5XEeqjr90pQBDU9w" x="786" y="255" width="146" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GgQxEI5YEeqjr90pQBDU9w" type="3027" element="_GgO74I5YEeqjr90pQBDU9w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_GgQxEo5YEeqjr90pQBDU9w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GgQxEY5YEeqjr90pQBDU9w" x="1153" y="255" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_L0sfII5YEeqjr90pQBDU9w" type="3062" element="_L0rRAI5YEeqjr90pQBDU9w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_L0sfIo5YEeqjr90pQBDU9w" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_L0sfI45YEeqjr90pQBDU9w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_L0sfIY5YEeqjr90pQBDU9w" x="1201" y="55"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kSA64I5eEeqjr90pQBDU9w" type="3005" element="_kR8pcI5eEeqjr90pQBDU9w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kSA64o5eEeqjr90pQBDU9w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kSA64Y5eEeqjr90pQBDU9w" x="954" y="151" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_r78gsI5eEeqjr90pQBDU9w" type="3008" element="_r77SkI5eEeqjr90pQBDU9w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_r78gso5eEeqjr90pQBDU9w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_r78gs45eEeqjr90pQBDU9w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r78gsY5eEeqjr90pQBDU9w" x="992" y="48"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qsgAII5gEeqjr90pQBDU9w" type="3009" element="_qseyAI5gEeqjr90pQBDU9w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_qsgnMY5gEeqjr90pQBDU9w" visible="false" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_qsgnMo5gEeqjr90pQBDU9w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qsgnMI5gEeqjr90pQBDU9w" x="992" y="263"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_40-9wI5gEeqjr90pQBDU9w" type="3062" element="_40-WsI5gEeqjr90pQBDU9w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_40_k0I5gEeqjr90pQBDU9w" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_40_k0Y5gEeqjr90pQBDU9w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_40-9wY5gEeqjr90pQBDU9w" x="1201" y="132"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_sfMnYI8REeqql-eK1hC8eA" type="3008" element="_sfLZQI8REeqql-eK1hC8eA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_sfMnYo8REeqql-eK1hC8eA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_sfNOcI8REeqql-eK1hC8eA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sfMnYY8REeqql-eK1hC8eA" x="306" y="263"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EkhzMI8TEeqql-eK1hC8eA" type="3008" element="_EkglEI8TEeqql-eK1hC8eA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_EkhzMo8TEeqql-eK1hC8eA" visible="false" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_EkhzM48TEeqql-eK1hC8eA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EkhzMY8TEeqql-eK1hC8eA" x="707" y="152"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_6Pyz4Y4pEeqjr90pQBDU9w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_6Pyz4o4pEeqjr90pQBDU9w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_6Pyz444pEeqjr90pQBDU9w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_6P0pEI4pEeqjr90pQBDU9w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6Pyz5I4pEeqjr90pQBDU9w" x="48" y="389" width="1364" height="361"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_Aqb8EI4qEeqjr90pQBDU9w" type="3007" element="_Aqat8I4qEeqjr90pQBDU9w">
          <children xmi:type="notation:DecorationNode" xmi:id="_AqcjII4qEeqjr90pQBDU9w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_AqcjIY4qEeqjr90pQBDU9w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_aGHagI5REeqjr90pQBDU9w" type="3005" element="_aGE-QI5REeqjr90pQBDU9w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_aGIBkI5REeqjr90pQBDU9w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_aGHagY5REeqjr90pQBDU9w" x="481" y="37" width="115" height="57"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tirg4I5REeqjr90pQBDU9w" type="3008" element="_tiq50I5REeqjr90pQBDU9w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_tirg4o5REeqjr90pQBDU9w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_tirg445REeqjr90pQBDU9w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tirg4Y5REeqjr90pQBDU9w" x="707" y="44" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eWZgsI8REeqql-eK1hC8eA" type="3027" element="_eV5KYI8REeqql-eK1hC8eA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_eWZgso8REeqql-eK1hC8eA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eWZgsY8REeqql-eK1hC8eA" x="479" y="147" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QzGTwI8REeqql-eK1hC8eA" type="3008" element="_QzEekI8REeqql-eK1hC8eA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_QzG60I8REeqql-eK1hC8eA" visible="false" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_QzG60Y8REeqql-eK1hC8eA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QzGTwY8REeqql-eK1hC8eA" x="112" y="155"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Aqb8EY4qEeqjr90pQBDU9w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Aqb8Eo4qEeqjr90pQBDU9w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Aqb8E44qEeqjr90pQBDU9w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_AqcjIo4qEeqjr90pQBDU9w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Aqb8FI4qEeqjr90pQBDU9w" x="48" y="788" width="1364" height="266"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_HcZ_II4qEeqjr90pQBDU9w" type="3007" element="_HcYJ8I4qEeqjr90pQBDU9w">
          <children xmi:type="notation:DecorationNode" xmi:id="_HcZ_JY4qEeqjr90pQBDU9w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_HcamMI4qEeqjr90pQBDU9w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_mgiMcI5UEeqjr90pQBDU9w" type="3063" element="_mgg-UI5UEeqjr90pQBDU9w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_mgiMco5UEeqjr90pQBDU9w" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mgiMcY5UEeqjr90pQBDU9w" x="255" y="56" width="146" height="73"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_HcZ_IY4qEeqjr90pQBDU9w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_HcZ_Io4qEeqjr90pQBDU9w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_HcZ_I44qEeqjr90pQBDU9w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_HcamMY4qEeqjr90pQBDU9w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HcZ_JI4qEeqjr90pQBDU9w" x="48" y="1054" width="1364" height="190"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_XbxtV44nEeq1tsXCfXZEaw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_XbxtWI4nEeq1tsXCfXZEaw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_XbxtWY4nEeq1tsXCfXZEaw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_XbxtWo4nEeq1tsXCfXZEaw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XbxtW44nEeq1tsXCfXZEaw" width="1387" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_XbxtXI4nEeq1tsXCfXZEaw"/>
    <edges xmi:type="notation:Connector" xmi:id="_PLejoI4qEeqjr90pQBDU9w" type="4001" element="_PLbgUI4qEeqjr90pQBDU9w" source="_XbxtTo4nEeq1tsXCfXZEaw" target="_QL3po44qEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PLgY0I4qEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PLgY0Y4qEeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PLejoY4qEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PLejoo4qEeqjr90pQBDU9w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_eGBQUI4qEeqjr90pQBDU9w" type="4001" element="_eF_bII4qEeqjr90pQBDU9w" source="_QL3po44qEeqjr90pQBDU9w" target="_0vyuII8dEeqql-eK1hC8eA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_eGB3YI4qEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_eGB3YY4qEeqjr90pQBDU9w" x="8" y="-13"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_eGBQUY4qEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_eGBQUo4qEeqjr90pQBDU9w" points="[0, 22, -1, -50]$[0, 44, -1, -28]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Od-dEI4tEeqjr90pQBDU9w" type="4001" element="_OdtXUI4tEeqjr90pQBDU9w" source="_QL3po44qEeqjr90pQBDU9w" target="_OdmpoI4tEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Od-dE44tEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Od-dFI4tEeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Od-dEY4tEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Od-dEo4tEeqjr90pQBDU9w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fBJ7gI4tEeqjr90pQBDU9w" type="4001" element="_fBJUcI4tEeqjr90pQBDU9w" source="_OdmpoI4tEeqjr90pQBDU9w" target="_avHekI4tEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fBJ7g44tEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fBJ7hI4tEeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fBJ7gY4tEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fBJ7go4tEeqjr90pQBDU9w" points="[-61, 33, -14, -94]$[-61, 106, -14, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fBLwsI4tEeqjr90pQBDU9w" id="(1.0,0.45)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fBLwsY4tEeqjr90pQBDU9w" id="(0.813953488372093,0.4883720930232558)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fxJOAI4tEeqjr90pQBDU9w" type="4001" element="_fxIm8I4tEeqjr90pQBDU9w" source="_vqY0EI4sEeqjr90pQBDU9w" target="_avHekI4tEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fxJ1EI4tEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fxJ1EY4tEeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fxJOAY4tEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fxJOAo4tEeqjr90pQBDU9w" points="[0, 11, -59, 12]$[50, 11, -9, 12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fxMRUI4tEeqjr90pQBDU9w" id="(1.0,0.35064935064935066)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fxMRUY4tEeqjr90pQBDU9w" id="(0.20930232558139536,0.20930232558139536)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_q2cugI4tEeqjr90pQBDU9w" type="4001" element="_q2bgYI4tEeqjr90pQBDU9w" source="_avHekI4tEeqjr90pQBDU9w" target="_mnyVsI4tEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_q2cug44tEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_q2cuhI4tEeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_q2cugY4tEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_q2cugo4tEeqjr90pQBDU9w" points="[-22, 11, 366, -53]$[-22, 63, 366, -1]$[-328, 63, 60, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_q2ejsI4tEeqjr90pQBDU9w" id="(1.0,0.7441860465116279)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4KIToo5EEeqjr90pQBDU9w" type="4001" element="_4KHskI5EEeqjr90pQBDU9w" source="_VWklMI4wEeqjr90pQBDU9w" target="_QzGTwI8REeqql-eK1hC8eA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4KI6sI5EEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4KI6sY5EEeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4KITo45EEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4KITpI5EEeqjr90pQBDU9w" points="[-65, 31, 1, -497]$[-65, 520, 1, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4KKv4I5EEeqjr90pQBDU9w" id="(1.0,0.5079365079365079)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_R8Xo8I8REeqql-eK1hC8eA" id="(0.4418604651162791,0.20930232558139536)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_v3WTMI5GEeqjr90pQBDU9w" type="4001" element="_v3VsII5GEeqjr90pQBDU9w" source="_XbxtS44nEeq1tsXCfXZEaw" target="_VWklMI4wEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_v3W6QI5GEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_v3W6QY5GEeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_v3WTMY5GEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_v3WTMo5GEeqjr90pQBDU9w" points="[-67, 41, 0, -117]$[-67, 127, 0, -31]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_v3YvcI5GEeqjr90pQBDU9w" id="(1.0,0.3787878787878788)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WErlYI5REeqjr90pQBDU9w" type="4001" element="_WEq-UI5REeqjr90pQBDU9w" source="_1X6OMI5FEeqjr90pQBDU9w" target="_Q7XiMI5REeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WErlY45REeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WErlZI5REeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WErlYY5REeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WErlYo5REeqjr90pQBDU9w" points="[0, 5, -104, -110]$[127, 5, 23, -110]$[127, 109, 23, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WEvPwI5REeqjr90pQBDU9w" id="(1.0,0.4090909090909091)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WEvPwY5REeqjr90pQBDU9w" id="(0.2833333333333333,0.1)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iUqwUI5REeqjr90pQBDU9w" type="4001" element="_iUqJQI5REeqjr90pQBDU9w" source="_Q7XiMI5REeqjr90pQBDU9w" target="_aGHagI5REeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iUrXYI5REeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iUrXYY5REeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iUqwUY5REeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iUqwUo5REeqjr90pQBDU9w" points="[-61, 32, 0, -365]$[-61, 394, 0, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iUtMkI5REeqjr90pQBDU9w" id="(1.0,0.4666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iUtMkY5REeqjr90pQBDU9w" id="(0.5,0.06)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tPzoMI5REeqjr90pQBDU9w" type="4001" element="_tPzBII5REeqjr90pQBDU9w" source="_aGHagI5REeqjr90pQBDU9w" target="_tirg4I5REeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tPzoM45REeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tPzoNI5REeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tPzoMY5REeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tPzoMo5REeqjr90pQBDU9w" points="[58, 0, -132, 0]$[169, 0, -21, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2QdwYI5REeqjr90pQBDU9w" type="4001" element="_2QdJUI5REeqjr90pQBDU9w" source="_tirg4I5REeqjr90pQBDU9w" target="_EkhzMI8TEeqql-eK1hC8eA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2QdwY45REeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2QdwZI5REeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2QdwYY5REeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2QdwYo5REeqjr90pQBDU9w" points="[-22, -35, -2, 257]$[-22, -283, -2, 9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2Qe-gI5REeqjr90pQBDU9w" id="(1.0,0.813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2Qe-gY5REeqjr90pQBDU9w" id="(0.5348837209302325,0.7906976744186046)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PIbIcI5SEeqjr90pQBDU9w" type="4001" element="_PIZTQI5SEeqjr90pQBDU9w" source="_4zRrYI5REeqjr90pQBDU9w" target="_Q7XiMI5REeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PIbvgI5SEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PIbvgY5SEeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PIbIcY5SEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PIbIco5SEeqjr90pQBDU9w" points="[-75, -6, 97, 3]$[-127, -6, 45, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PIeLwI5SEeqjr90pQBDU9w" id="(1.0,0.62)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cW7-4I5XEeqjr90pQBDU9w" type="4001" element="_cWoc4I5XEeqjr90pQBDU9w" source="_I8vh845VEeqjr90pQBDU9w" target="_eQLYfI5XEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cW7-445XEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cW7-5I5XEeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cW7-4Y5XEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cW7-4o5XEeqjr90pQBDU9w" points="[22, 0, -204, -2]$[153, 0, -73, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GgVCgI5YEeqjr90pQBDU9w" type="4001" element="_GgUbcI5YEeqjr90pQBDU9w" source="_eQLYfI5XEeqjr90pQBDU9w" target="_qsgAII5gEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GgVpkI5YEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GgVpkY5YEeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GgVCgY5YEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GgVCgo5YEeqjr90pQBDU9w" points="[73, -2, -62, 7]$[133, -2, -2, 7]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_to78EI5gEeqjr90pQBDU9w" id="(0.046511627906976744,0.32558139534883723)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zrJ9MI5gEeqjr90pQBDU9w" type="4001" element="_zrIvEI5gEeqjr90pQBDU9w" source="_qsgAII5gEeqjr90pQBDU9w" target="_kSA64I5eEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zrKkQI5gEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zrKkQY5gEeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zrJ9MY5gEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zrJ9Mo5gEeqjr90pQBDU9w" points="[-22, -33, 59, 92]$[-22, -85, 59, 40]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zrMZcI5gEeqjr90pQBDU9w" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zrNAgI5gEeqjr90pQBDU9w" id="(0.0,0.3333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0E2PkI5gEeqjr90pQBDU9w" type="4001" element="_0E1ogI5gEeqjr90pQBDU9w" source="_qsgAII5gEeqjr90pQBDU9w" target="_GgQxEI5YEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0E2Pk45gEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0E2PlI5gEeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0E2PkY5gEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0E2Pko5gEeqjr90pQBDU9w" points="[0, -14, -181, -2]$[118, -14, -63, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0E3dsI5gEeqjr90pQBDU9w" id="(1.0,0.813953488372093)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_41DPMI5gEeqjr90pQBDU9w" type="4001" element="_41CoII5gEeqjr90pQBDU9w" source="_GgQxEI5YEeqjr90pQBDU9w" target="_40-9wI5gEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_41DPM45gEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_41DPNI5gEeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_41DPMY5gEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_41DPMo5gEeqjr90pQBDU9w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6kHZEI5gEeqjr90pQBDU9w" type="4001" element="_6kGyAI5gEeqjr90pQBDU9w" source="_kSA64I5eEeqjr90pQBDU9w" target="_r78gsI5eEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6kIAII5gEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6kIAIY5gEeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6kHZEY5gEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6kHZEo5gEeqjr90pQBDU9w" points="[-61, -33, 0, 82]$[-61, -93, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6kJOQI5gEeqjr90pQBDU9w" id="(1.0,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-2AFA45gEeqjr90pQBDU9w" type="4001" element="_-2AFAI5gEeqjr90pQBDU9w" source="_r78gsI5eEeqjr90pQBDU9w" target="_L0sfII5YEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-2AsEo5gEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-2AsE45gEeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-2AsEI5gEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-2AsEY5gEeqjr90pQBDU9w" points="[0, -13, -181, 6]$[167, -13, -14, 6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-2ChQI5gEeqjr90pQBDU9w" id="(1.0,0.7906976744186046)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AM60oI5hEeqjr90pQBDU9w" type="4001" element="_AMq9AI5hEeqjr90pQBDU9w" source="_r78gsI5eEeqjr90pQBDU9w" target="_4zRrYI5REeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AM60o45hEeqjr90pQBDU9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AM60pI5hEeqjr90pQBDU9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AM60oY5hEeqjr90pQBDU9w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AM60oo5hEeqjr90pQBDU9w" points="[-42, -10, 232, -2]$[-216, -10, 58, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AM8CwI5hEeqjr90pQBDU9w" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cpKYQI8QEeqql-eK1hC8eA" type="4001" element="_cpJKII8QEeqql-eK1hC8eA" source="_mnyVsI4tEeqjr90pQBDU9w" target="_XbxtS44nEeq1tsXCfXZEaw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cpKYQ48QEeqql-eK1hC8eA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cpKYRI8QEeqql-eK1hC8eA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cpKYQY8QEeqql-eK1hC8eA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cpKYQo8QEeqql-eK1hC8eA" points="[-61, 28, 0, -353]$[-61, 348, 0, -33]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cpMNcI8QEeqql-eK1hC8eA" id="(1.0,0.5333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fcmJMI8QEeqql-eK1hC8eA" type="4001" element="_fck7EI8QEeqql-eK1hC8eA" source="_mgiMcI5UEeqjr90pQBDU9w" target="_sfMnYI8REeqql-eK1hC8eA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fcmJM48QEeqql-eK1hC8eA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fcmJNI8QEeqql-eK1hC8eA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fcmJMY8QEeqql-eK1hC8eA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fcmJMo8QEeqql-eK1hC8eA" points="[-74, -32, 0, 437]$[-74, -447, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fcn-YI8QEeqql-eK1hC8eA" id="(1.0,0.4383561643835616)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_eXwyoI8REeqql-eK1hC8eA" type="4001" element="_eWgOYI8REeqql-eK1hC8eA" source="_tirg4I5REeqjr90pQBDU9w" target="_eWZgsI8REeqql-eK1hC8eA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_eXwyo48REeqql-eK1hC8eA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_eXwypI8REeqql-eK1hC8eA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_eXwyoY8REeqql-eK1hC8eA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_eXwyoo8REeqql-eK1hC8eA" points="[-2, 19, 187, -93]$[-2, 111, 187, -1]$[-129, 111, 60, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_e9D4EI8REeqql-eK1hC8eA" type="4001" element="_e9DRAI8REeqql-eK1hC8eA" source="_eWZgsI8REeqql-eK1hC8eA" target="_QzGTwI8REeqql-eK1hC8eA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_e9D4E48REeqql-eK1hC8eA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_e9D4FI8REeqql-eK1hC8eA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_e9D4EY8REeqql-eK1hC8eA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_e9D4Eo8REeqql-eK1hC8eA" points="[-100, -6, 203, -8]$[-295, -12, 8, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_e9FGMI8REeqql-eK1hC8eA" id="(1.0,0.52)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_i1BoII8REeqql-eK1hC8eA" type="4001" element="_i1AaAI8REeqql-eK1hC8eA" source="_QzGTwI8REeqql-eK1hC8eA" target="_mgiMcI5UEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_i1BoI48REeqql-eK1hC8eA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_i1BoJI8REeqql-eK1hC8eA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_i1BoIY8REeqql-eK1hC8eA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_i1BoIo8REeqql-eK1hC8eA" points="[-22, 13, -195, -160]$[-22, 175, -195, 2]$[100, 175, -73, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_i1DdUI8REeqql-eK1hC8eA" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_sfXmgI8REeqql-eK1hC8eA" type="4001" element="_sfWYYI8REeqql-eK1hC8eA" source="_sfMnYI8REeqql-eK1hC8eA" target="_1X6OMI5FEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sfYNkI8REeqql-eK1hC8eA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sfYNkY8REeqql-eK1hC8eA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sfXmgY8REeqql-eK1hC8eA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sfXmgo8REeqql-eK1hC8eA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JDyCMI8SEeqql-eK1hC8eA" type="4001" element="_JDMzYI8SEeqql-eK1hC8eA" source="_sfMnYI8REeqql-eK1hC8eA" target="_I8vh845VEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JDypQI8SEeqql-eK1hC8eA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JDypQY8SEeqql-eK1hC8eA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JDyCMY8SEeqql-eK1hC8eA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JDyCMo8SEeqql-eK1hC8eA" points="[-13, 0, -270, 11]$[249, -11, -8, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JD1FgI8SEeqql-eK1hC8eA" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JD1FgY8SEeqql-eK1hC8eA" id="(0.20930232558139536,0.5116279069767442)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_G8izcI8TEeqql-eK1hC8eA" type="4001" element="_G756QI8TEeqql-eK1hC8eA" source="_I8vh845VEeqjr90pQBDU9w" target="_EkhzMI8TEeqql-eK1hC8eA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_G8izc48TEeqql-eK1hC8eA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_G8izdI8TEeqql-eK1hC8eA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_G8izcY8TEeqql-eK1hC8eA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_G8izco8TEeqql-eK1hC8eA" points="[-22, -30, -95, 90]$[-22, -120, -95, 0]$[52, -120, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_G8lPsI8TEeqql-eK1hC8eA" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IOLacI8TEeqql-eK1hC8eA" type="4001" element="_IOKMUI8TEeqql-eK1hC8eA" source="_EkhzMI8TEeqql-eK1hC8eA" target="_4zRrYI5REeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IOLac48TEeqql-eK1hC8eA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IOLadI8TEeqql-eK1hC8eA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IOLacY8TEeqql-eK1hC8eA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IOLaco8TEeqql-eK1hC8eA" points="[-22, -28, -13, 67]$[-22, -81, -13, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IONPoI8TEeqql-eK1hC8eA" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IONPoY8TEeqql-eK1hC8eA" id="(0.603448275862069,0.7586206896551724)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0v5b0I8dEeqql-eK1hC8eA" type="4001" element="_0v4NsI8dEeqql-eK1hC8eA" source="_0vyuII8dEeqql-eK1hC8eA" target="_vqY0EI4sEeqjr90pQBDU9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0v6C4I8dEeqql-eK1hC8eA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0v6C4Y8dEeqql-eK1hC8eA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0v5b0Y8dEeqql-eK1hC8eA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0v5b0o8dEeqql-eK1hC8eA" points="[-1, 28, -155, -55]$[-1, 87, -155, 4]$[84, 87, -70, 4]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
